# COS760 2025 — Natural Language Processing
## Project: Detecting Machine-Generated Texts in African Languages

**Authors:**  
Sithembisiso, Thabang, Edwin

---

### Objective
Develop models to distinguish between human-written and machine-generated texts in African languages.

### Datasets
| Dataset | Type | Description |
|---|---|---|
| **AfriSenti** | Human | Twitter sentiment corpus covering 16+ African languages |
| **Vukuzenzele** | Human | South African government multilingual corpus (11 official languages) |
| **Common Crawl (CC-100)** | Human | Web-crawl text filtered for African languages |
| **GPT-Generated Texts** | Machine | Texts produced by GPT models in African languages |

### This Notebook
This notebook focuses purely on **data loading and exploration**:
1. Load each dataset from its source
2. Show which languages are present and how many lines each contains
3. Inspect columns and display the first 5 rows per language

---
## 0. Setup — Install and Import Packages

In [ ]:
# Install required libraries (only needed once in Colab / fresh environment)
!pip install datasets huggingface_hub -q

In [ ]:
import os
import pickle
import glob
import subprocess
import warnings
import logging
import re

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from datasets import load_dataset
from datasets.utils.logging import disable_progress_bar
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, f1_score, classification_report
from google.colab import drive

drive.mount('/content/drive')
disable_progress_bar()
warnings.filterwarnings('ignore')
logging.disable(logging.CRITICAL)

# Make DataFrames easier to read in output cells
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_columns', 20)
pd.set_option('display.expand_frame_repr', False)

print("All packages imported successfully.")

Mounted at /content/drive
All packages imported successfully.

---
## 1. AfriSenti Dataset

**AfriSenti** is a large-scale Twitter sentiment analysis corpus for African languages, introduced as part of SemEval-2023 Task 12.  
It provides human-written tweets labelled *positive*, *negative*, or *neutral* and is one of the richest sources of authentic African-language text available.

- **Source:** [`masakhane/afrisenti`](https://huggingface.co/datasets/masakhane/afrisenti) on HuggingFace  
- **Languages covered:** Amharic, Hausa, Igbo, Kinyarwanda, Oromo, Nigerian Pidgin, chiShona, Somali, Swahili, Tigrinya, Twi, Yoruba  
- **Splits:** train / dev / test per language  
- **Role in this project:** Source of *human-written* text for classifier training

In [ ]:
AFRISENTI_LANGUAGES = {
    'amh': 'Amharic',
    'hau': 'Hausa',
    'ibo': 'Igbo',
    'kin': 'Kinyarwanda',
    'orm': 'Oromo',
    'pcm': 'Nigerian Pidgin',
    'sna': 'chiShona',
    'som': 'Somali',
    'swa': 'Swahili',
    'tir': 'Tigrinya',
    'twi': 'Twi',
    'yor': 'Yoruba',
}

afrisenti_dfs = {}

for lang_code, lang_name in AFRISENTI_LANGUAGES.items():
    try:
        ds = load_dataset("masakhane/afrisenti", lang_code)
        split_dfs = []
        for split_name in ds:
            split_df = pd.DataFrame(ds[split_name])
            split_df['split'] = split_name
            split_dfs.append(split_df)
        lang_df = pd.concat(split_dfs, ignore_index=True)
        lang_df['language_code'] = lang_code
        lang_df['language_name'] = lang_name
        afrisenti_dfs[lang_code] = lang_df
        print(f"  [OK]   {lang_code}  —  {len(lang_df):,} rows")
    except Exception:
        print(f"  [SKIP] {lang_code}  —  not available")

afrisenti_df = pd.concat(afrisenti_dfs.values(), ignore_index=True) if afrisenti_dfs else pd.DataFrame()
print(f"\n  Total rows loaded: {len(afrisenti_df):,}")

README.md: 0.00B [00:00, ?B/s]

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   amh  —  9,480 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   hau  —  22,152 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   ibo  —  15,715 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   kin  —  5,155 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   orm  —  14,255 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   pcm  —  10,556 rows
  [SKIP] sna  —  not available
  [SKIP] som  —  not available

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   swa  —  3,011 rows

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   tir  —  14,161 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   twi  —  4,818 rows

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

  [OK]   yor  —  15,127 rows

  Total rows loaded: 114,430

### 1.1 Languages and Line Counts
The table below shows each language present in the loaded AfriSenti data and how many lines (rows) it contributes.

In [ ]:
afrisenti_summary = (
    afrisenti_df
    .groupby(['language_code', 'language_name'])
    .size()
    .reset_index(name='num_lines')
    .rename(columns={'language_code': 'Language Code', 'language_name': 'Language', 'num_lines': 'Number of Lines'})
    .sort_values('Number of Lines', ascending=False)
    .reset_index(drop=True)
)

print(f"AfriSenti — {len(afrisenti_summary)} languages loaded\n")
display(afrisenti_summary)

AfriSenti — 10 languages loaded

  Language Code         Language  Number of Lines
0           hau            Hausa            22152
1           ibo             Igbo            15715
2           yor           Yoruba            15127
3           orm            Oromo            14255
4           tir         Tigrinya            14161
5           pcm  Nigerian Pidgin            10556
6           amh          Amharic             9480
7           kin      Kinyarwanda             5155
8           twi              Twi             4818
9           swa          Swahili             3011

### 1.2 Columns and First 5 Rows per Language

In [ ]:
print("AfriSenti columns:", afrisenti_df.columns.tolist())
print()

for lang_code, lang_name in AFRISENTI_LANGUAGES.items():
    if lang_code not in afrisenti_dfs:
        continue
    print(f"{'='*70}")
    print(f"  Language: {lang_name} ({lang_code})")
    print(f"{'='*70}")
    display(afrisenti_dfs[lang_code].head(5))
    print()

AfriSenti columns: ['tweet', 'label', 'split', 'language_code', 'language_name']

======================================================================
  Language: Amharic (amh)
======================================================================

                                                                                                               tweet     label  split language_code language_name
0                                                         Tesfaye ለካስ ጭብል ለብሰሽ የፕሮፌሰርን ፎቶ ለጥፈክ እልም ያልክ ባዳ ነክ እፈር ትንሽ  negative  train           amh       Amharic
1                                             ይሄው ነው አይደል የእውቀትሽ ጥግ....በሰሚ ሰሚ ከምትናገሪ ለምን ታሪክ አታነቢም....ደሞ ራስሽን አታስገምቺ  negative  train           amh       Amharic
2                                                                                ዘገበ ይባላል? ሌላ የሚባል ነገር ካለ አንተዉ ንገረን!  negative  train           amh       Amharic
3  ?? ድሮ በዘመነ ኮዳክ ፎቶ ቤት ፍላሹ ፏ ሲል አይናችን ተጨፍኖ እንዳይወጣ የምንቸክለውን ነገር አስታወሰኝ ???? ምን ሆኖ ነው ግን? ከሗላ ያለው ቴዲ ሁሉ ፊቱን አዞረ እኮ ??  negative  train           amh       Amharic
4                                                                                                     ዠልጥ?? ???? ገገማ  negative  train           amh       Amharic

======================================================================
  Language: Hausa (hau)
======================================================================

                                                                                                                     tweet     label  split language_code language_name
0  @user Da kudin da Arewa babu wani abin azo agani da yayi wa alummah allah ya isa yacucemu wlh yarikitamana kasa yari...  negative  train           hau         Hausa
1  @user Kaga wani Adu ar Banda💔😭 wai a haka Shi ne shugaban sojoji.... Gaskiya Buhari kaci Amanan mu da kasa wannan mu...  negative  train           hau         Hausa
2                                                    @user Sai haquri fa yan madrid daman kunce champion din ya muku yawa😂  negative  train           hau         Hausa
3  @user Hmmm yanzu kai kasan girman allah daxakace mukuma ga Allah kune kukabarshi kuna karyata ayoyinsa kace allah ba...  negative  train           hau         Hausa
4                                                                 @user @user Wai gwamno nin Nigeria suna afa kwayoyi ko 😂  negative  train           hau         Hausa

======================================================================
  Language: Igbo (ibo)
======================================================================

                                                         tweet     label  split language_code language_name
0                 Nna Ike Gwuru ooo. 😂 https://t.co/NDS7juFBGd  negative  train           ibo          Igbo
1                           @user Chineke nna kezi mgbe ole???  negative  train           ibo          Igbo
2    Lol. Isi adirokwanu gi nma.. 😐😒😒😒 https://t.co/5gzmgYk6RW  negative  train           ibo          Igbo
3  @user haha. Fulani herdsmen. akpa amu gi retweet. Rie nsi 😝  negative  train           ibo          Igbo
4      Nna ghetto di gi na aru biko!!! https://t.co/4G9bzI4uKG  negative  train           ibo          Igbo

======================================================================
  Language: Kinyarwanda (kin)
======================================================================

                                                                                               tweet     label  split language_code language_name
0          @user @user @user @user @user @user @user Hhhhhh ntabyihogoza, ubu x abo yishe bangana ik  negative  train           kin   Kinyarwanda
1                             @user Amahano?! Ni impanuka, inkangu, inzara.... Muyite izina rikwiye.  negative  train           kin   Kinyarwanda
2  Ese umuntu aguhaye miliyoni 7 zidorali ngo aryamane numugore wawe cg umukunzi wawe wabyemera🙄????  negative  train           kin   Kinyarwanda
3      Ugira amagambo😏 kandi Ubwo wasanga nawe byagutabara. Jya uvuga uziga😏 https://t.co/9OWOZxquFO  negative  train           kin   Kinyarwanda
4           Ukuntu inama zose zikomeye zirikubera Mu Rwanda ubanza numusi wimperuka uzabera kigali 🤔  negative  train           kin   Kinyarwanda

======================================================================
  Language: Oromo (orm)
======================================================================

                                                                                                                     tweet     label  split language_code language_name
0         sorry you had that weird disturbance on sunday im the random guy that helped out please give my thanks to justin   neutral  train           orm         Oromo
1                        if you have amazon prime it may be for you best buy is dropping the cost of the fire stick i hear   neutral  train           orm         Oromo
2  harpers new ad i am who i am not perfect but depend on me for economy harper slip sliding down the pollsrd we know w...  negative  train           orm         Oromo
3               who is funding these chris christie ads st jude couldnt get him the nomination may as well be bobby jindal  negative  train           orm         Oromo
4                                                     im going to chris brown at isleta amphitheater in albuquerque nm sep  positive  train           orm         Oromo

======================================================================
  Language: Nigerian Pidgin (pcm)
======================================================================

                                                                                                                     tweet     label  split language_code    language_name
0                                 yeah ‍️the guy wants to trend dat was why e join nysc e cant trend with good music again  negative  train           pcm  Nigerian Pidgin
1  this life is so funny sef you will work hard and buy cloths and shoes and rain will start dictating when to wear the...  negative  train           pcm  Nigerian Pidgin
2  dis is unfair of urcompany goingtowks nw ive bin complaining abt d subscriptioni did wch did nt reflect on mydecoder...  negative  train           pcm  Nigerian Pidgin
3                                                                       lil wayne don vex me im actually not excited again  negative  train           pcm  Nigerian Pidgin
4  dis is unfair of ur company going to wks nw ive bin complaining abt d subscriptioni did wch did nt reflect on mydeco...  negative  train           pcm  Nigerian Pidgin

======================================================================
  Language: Swahili (swa)
======================================================================

                                                                                                                     tweet     label  split language_code language_name
0         Kwani tanesco wanakataga umeme makusudinadhani kuna changamoto behind zinatakiwa zitatuliwe na sio kutoa matamko  negative  train           swa       Swahili
1  cjawahi kuona content yoyote zaidi ya kuwa analalamika cjawahi kuona akitafuta solution ya tattizo zaid ya kulalamik...  negative  train           swa       Swahili
2  Bomu lililokuwa limetegwa ndani ya gari likiwalenga wajenzi kutoka Uturuki limelipuka katika eneo la Afgoye kaskazin...  negative  train           swa       Swahili
3   Kuna video inasambaa mitandaoni jamaa amemfumania mkewe akiwa na jamaa mwingine huku akimlalamikia jamaa akimwambia kw  negative  train           swa       Swahili
4  Viwavijeshi wanapita katika hatua kuu 6 za ukuaji katika hatua yake ya larvae mayai 10001500 hutagwa na larvae mmoja...  negative  train           swa       Swahili

======================================================================
  Language: Tigrinya (tir)
======================================================================

                                                                                                                     tweet     label  split language_code language_name
0         sorry you had that weird disturbance on sunday im the random guy that helped out please give my thanks to justin   neutral  train           tir      Tigrinya
1                        if you have amazon prime it may be for you best buy is dropping the cost of the fire stick i hear   neutral  train           tir      Tigrinya
2  harpers new ad i am who i am not perfect but depend on me for economy harper slip sliding down the pollsrd we know w...  negative  train           tir      Tigrinya
3               who is funding these chris christie ads st jude couldnt get him the nomination may as well be bobby jindal  negative  train           tir      Tigrinya
4                                                     im going to chris brown at isleta amphitheater in albuquerque nm sep  positive  train           tir      Tigrinya

======================================================================
  Language: Twi (twi)
======================================================================

                                                                                                                   tweet     label  split language_code language_name
0                                                                                            kako be shark but wo ti ewu  negative  train           twi           Twi
1                                                                                br ne bayie nti na me supporti man city  negative  train           twi           Twi
2  s3 woofis3 mada wafutuo tantan no 3y3wo s3mafa dabiaa mekaewos3 menny3 celebrity s3 wodidimat3ma menso m3yeya wo nana  negative  train           twi           Twi
3                                                                              wabɔdam anaa wo trumu yɛ nkate nkwan aseɛ  negative  train           twi           Twi
4                                                                                                      enfa bi da bra 🤣🤣  negative  train           twi           Twi

======================================================================
  Language: Yoruba (yor)
======================================================================

                                                                                                                     tweet     label  split language_code language_name
0                     Ìwọ ikú òpònú abaradúdú wọ, o ò ṣe é 're o. O d'óró, o ṣ'èkà, o m'ẹ́ni rere lọ. @user ṣe bẹ́ẹ̀ ó lọ.  negative  train           yor        Yoruba
1                                      Yorùbá nbú'yàn ṣá """"""""..àyà wanle bí òkú ìbànújẹ́"""""""" áha! :) #eebu #Yoruba  negative  train           yor        Yoruba
2  Òwe àgbà ní """"""""ọmọlọ́mọ là á rán níṣẹ́ à á dé lóru"""""""", ẹ wí fún wọ́n pé kí wọ́n ó rán'mọ wọn. Wọ́n kì í mú...  negative  train           yor        Yoruba
3  RT @user: @user asa kasa ti awon eyan ko ni odo awon oyinbo tiko mu ogbon wa, koda rara,atipe ounse okunfa alebu ati...  negative  train           yor        Yoruba
4  RT @user: Mo ń rí àwọn èébú kọ̀ọ̀kan. Àti àwọn tí wọ́n ń fi wá ṣe yẹ̀yẹ́. Ẹ fiwọ́n sílẹ̀, ara ló ń ta wọ́n. Àwa ò ní...  negative  train           yor        Yoruba

---
## 2. Vukuzenzele Dataset

**Vukuzenzele** is a South African government multilingual corpus built by the DSFSI group at the University of Pretoria.  
It contains text extracted from the *Vukuzenzele* government magazine, which is published in all 11 official South African languages, making it a unique source of parallel and monolingual African-language text.

- **Source:** [`dsfsi/vukuzenzele-monolingual-corpus`](https://huggingface.co/datasets/dsfsi/vukuzenzele-monolingual-corpus) on HuggingFace  
- **Languages covered:** Afrikaans, English, isiNdebele, Sepedi (Northern Sotho), Sesotho, siSwati, Xitsonga, Setswana, Tshivenda, isiXhosa, isiZulu  
- **Role in this project:** Source of *human-written* formal/government text

In [ ]:

REPO_URL  = "https://github.com/dsfsi/vukuzenzele-nlp.git"
LOCAL_DIR = "vukuzenzele-nlp"

if os.path.isdir(LOCAL_DIR):
    print("Repo exists. Updating...")
    subprocess.run(["git", "-C", LOCAL_DIR, "pull", "-q"], check=True)
else:
    print("Cloning Vukuzenzele repo...")
    subprocess.run(["git", "clone", REPO_URL, "--depth=1", "-q"], check=True)

VUKUZENZELE_LANGUAGES = {
    'afr': 'Afrikaans',
    'eng': 'English',
    'nbl': 'isiNdebele',
    'nso': 'Sepedi (Northern Sotho)',
    'sot': 'Sesotho',
    'ssw': 'siSwati',
    'tso': 'Xitsonga',
    'tsn': 'Setswana',
    'ven': 'Tshivenda',
    'xho': 'isiXhosa',
    'zul': 'isiZulu',
}

def extract_sentences(text, min_words=5):
    """Split article text into sentences."""
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s.strip() for s in sentences if len(s.split()) >= min_words]

processed_dir  = os.path.join(LOCAL_DIR, "data", "processed")
vukuzenzele_dfs = {}
print("Loading Vukuzenzele from GitHub repo...\n")

for lang_code, lang_name in VUKUZENZELE_LANGUAGES.items():
    sentences = []

    # Files are .txt named like: 2020-07-ed2-vukuzenzele-zul-001.txt
    for root, _, files in os.walk(processed_dir):
        for fname in files:
            if fname.endswith('.txt') and f'-{lang_code}-' in fname:
                fpath = os.path.join(root, fname)
                with open(fpath, encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                sentences.extend(extract_sentences(content))

    if sentences:
        sentences = list(dict.fromkeys(sentences))   # deduplicate
        lang_df = pd.DataFrame({'text': sentences})
        lang_df['language_code'] = lang_code
        lang_df['language_name'] = lang_name
        vukuzenzele_dfs[lang_code] = lang_df
        print(f"  [OK]   {lang_code}  —  {len(lang_df):,} sentences")
    else:
        print(f"  [SKIP] {lang_code}  —  no files found")

vukuzenzele_df = pd.concat(vukuzenzele_dfs.values(), ignore_index=True) if vukuzenzele_dfs else pd.DataFrame()
print(f"\n  Total sentences loaded: {len(vukuzenzele_df):,}")

Cloning Vukuzenzele repo...
Loading Vukuzenzele from GitHub repo...

  [OK]   afr  —  4,515 sentences
  [OK]   eng  —  3,551 sentences
  [OK]   nbl  —  4,677 sentences
  [OK]   nso  —  4,273 sentences
  [OK]   sot  —  4,294 sentences
  [OK]   ssw  —  4,287 sentences
  [OK]   tso  —  4,265 sentences
  [OK]   tsn  —  4,069 sentences
  [OK]   ven  —  4,338 sentences
  [OK]   xho  —  4,304 sentences
  [OK]   zul  —  4,226 sentences

  Total sentences loaded: 46,799

### 2.1 Languages and Line Counts

In [ ]:
vukuzenzele_summary = (
    vukuzenzele_df
    .groupby(['language_code', 'language_name'])
    .size()
    .reset_index(name='num_lines')
    .rename(columns={'language_code': 'Language Code', 'language_name': 'Language', 'num_lines': 'Number of Lines'})
    .sort_values('Number of Lines', ascending=False)
    .reset_index(drop=True)
)

print(f"Vukuzenzele — {len(vukuzenzele_summary)} languages loaded\n")
display(vukuzenzele_summary)

Vukuzenzele — 11 languages loaded

   Language Code                 Language  Number of Lines
0            nbl               isiNdebele             4677
1            afr                Afrikaans             4515
2            ven                Tshivenda             4338
3            xho                 isiXhosa             4304
4            sot                  Sesotho             4294
5            ssw                  siSwati             4287
6            nso  Sepedi (Northern Sotho)             4273
7            tso                 Xitsonga             4265
8            zul                  isiZulu             4226
9            tsn                 Setswana             4069
10           eng                  English             3551

### 2.2 Columns and First 5 Rows per Language

In [ ]:
print("Vukuzenzele columns:", vukuzenzele_df.columns.tolist())
print()

for lang_code, lang_name in VUKUZENZELE_LANGUAGES.items():
    if lang_code not in vukuzenzele_dfs:
        continue
    print(f"{'='*70}")
    print(f"  Language: {lang_name} ({lang_code})")
    print(f"{'='*70}")
    display(vukuzenzele_dfs[lang_code].head(10))
    print()

Vukuzenzele columns: ['text', 'language_code', 'language_name']

======================================================================
  Language: Afrikaans (afr)
======================================================================

                                                                                                                      text language_code language_name
0  NSFAS het my drome bewaarheid  \n\nMore Matshediso \n\nDie Nasionale Fi nansiële Hulp skema vir Studente  (NSFAS) he...           afr     Afrikaans
1  Mashego, van Sebokeng in Gauteng se Vaal-omgewing, sê hy sou nooit die klasgeld en die ander uitgawes ver bonde aan ...           afr     Afrikaans
2  “Die maandelikse toelaag wat ek van NSFAS ontvang, stel my ook in staat om met 'n vol maag te gaan slaap en te stude...           afr     Afrikaans
3   Mashego is 'n derdejaar student wat vir ‘n graad in siviele ingenieurswese aan die Universiteit van Preto ria studeer.           afr     Afrikaans
4  Ek sou nie eers kon bekostig om vir die eerste semester van die kursus wat ek gekies het te betaal nie, wat nog te s...           afr     Afrikaans
5  Mashego het in 2016 ma trikuleer en was een van die toppresteerders in sy klas, maar het nie geld gehad om vir verde...           afr     Afrikaans
6                                         Sy aansoek om NSFAS-befondsing vir die 2018 akademiese jaar was egter suksesvol.           afr     Afrikaans
7                              “Dit het my die geleent heid gegee om my droom om ingenieurswese te stu deer te bewaarheid.           afr     Afrikaans
8  Onder rig speel ’n baie belangrike rol in my persoonlike ont wikkeling en help my om vordering te maak met alles wat...           afr     Afrikaans
9  Dit stel my ook in staat om ander mense in my gemeenskap te bemagtig en sodoende tot die land se ekonomie by te dra,...           afr     Afrikaans

======================================================================
  Language: English (eng)
======================================================================

                                                                                                                      text language_code language_name
0  Let’s keep each other safe\n\nvukuzenzele unnamed\n\nOur country has moved to alert level 2 in our response to the c...           eng       English
1  This has come as a relief to all South Africans who have had to live under stringent restrictions for the last five ...           eng       English
2               It is a sign of the progress we are making in reducing new infections and demand on our health facilities.           eng       English
3                                             It is also a very important development as we strive to restart our economy.           eng       English
4                                                                                         But it is too soon to celebrate.           eng       English
5        We are still very much in the middle of a deadly pandemic that has taken over 11,000 lives in South Africa alone.           eng       English
6          At more than half a million confirmed cases, we still have the fifth highest number of infections in the world.           eng       English
7                                                             And there is always a chance of a resurgence of the disease.           eng       English
8  If we ever need a stark reminder of the need for vigilance, we should look to recent events thousands of kilometres ...           eng       English
9                  Three months since the country was declared coronavirus-free, New Zealand is once again under lockdown.           eng       English

======================================================================
  Language: isiNdebele (nbl)
======================================================================

                                                                                                                      text language_code language_name
0  I-NSFAS Iphumelelise Amabhudangwami\n\nMore Matshediso \n\nIsiKhwama seli Zweloke seSizo lee Mali zokuFunda  (i-NSFA...           nbl    isiNdebele
1  U-Karabo we-Sebokeng endaweni ye-Vaal engeGauteng uthi bekangeze akghone ukubhadela iimali zokufunda nezinye iindlek...           nbl    isiNdebele
2  Uthi, “Okhunye godu, isi bonelelo saqobe yinyanga engisifumana ku-NSFAS singisiza ukulala noku funda ngidlile,” U-Ka...           nbl    isiNdebele
3                                                                          Uhlathulule wathi, “Iimali zokufunda ziphezulu.           nbl    isiNdebele
4  Ii mfundo engizikhethileko, bengingeze ngazifikelela nokubhadelela isiquntu somnyaka, ngingasakhulu mi-ke ngomnyaka ...           nbl    isiNdebele
5                                   Wenza isibawo esaphumele lako sesekelo leemali kwa NSFAS somnyaka woku funda wee-2018.           nbl    isiNdebele
6        U-Karabo uhlathulule wathi, “Lokhu kwangini kela ithuba lokuphume lelisa ibhudango lami lokufundela ubunjiniyera.           nbl    isiNdebele
7     Ifundo inendima ekulu ekuzithuthukiseni kwami begodu iyangisiza uku thuthuka kikho koke engi funa ukufikelela kikho.           nbl    isiNdebele
8  Khulukhulu, kuyangi siza ukuthuthukisa abanye abantu emphakathinethu ngendlela leyo ngifake isandla emnothweni weli ...           nbl    isiNdebele
9  Blade Nzimande, uvule umzombe wokuthu mela iimbawo zomnyaka wee-2021 ku-NSFAS ozo kuraga iinyanga ezine, ukusukela m...           nbl    isiNdebele

======================================================================
  Language: Sepedi (Northern Sotho) (nso)
======================================================================

                                                                                                                      text language_code            language_name
0  NSFAS e phethagatša ditoro tša ka\n\nMore Matshediso \n\nSetlamo sa Setšhaba sa Thušo ya  Ditšhelete tša  Baithuti (...           nso  Sepedi (Northern Sotho)
1  Mashego wa go tšwa Sebo keng profenseng ya Gauteng tikologong ya Vaal o bolela gore a ka be a sa kgona go fihlelela ...           nso  Sepedi (Northern Sotho)
2  “Godimo ga mo, tšhelete ya kgwedi ka kgwedi yeo ke e hwetšago go tšwa NSFAS e nkgontšha gore ke ithute le gore ke se...           nso  Sepedi (Northern Sotho)
3  Mashego ke moithuti wa ngwaga wa boraro dithutong tša gagwe tša lengwalo la degree ya civil engineering  kua Yunibes...           nso  Sepedi (Northern Sotho)
4                                                                                   “Ditefelo tša thuto di tura ka maatla.           nso  Sepedi (Northern Sotho)
5  Ka dithuto tšeo ke di kgethilego, nkabe ke saka ka kgona go lefela dikgwedi tše tshela, ke sa bolele ka ngwaga o tee...           nso  Sepedi (Northern Sotho)
6  Mashego o feditše mare matlou ka 2016 e le moithuti wa go šoma bokaonekaone ka mphatong wa gagwe, eupša o be a hloka...           nso  Sepedi (Northern Sotho)
7                  O ile a atlega dikgopelong tša gagwe tša thekgo ya tšhelete go tšwa NSFAS ka ngwaga wa dithuto wa 2018.           nso  Sepedi (Northern Sotho)
8                                      “Se se mphile monyetla wa go dira toro yaka ya go ithutela engineering go ba nnete.           nso  Sepedi (Northern Sotho)
9  Thuto e kgatha tema ye bohlokwa kudu tlhabo llong yaka ebile e nthuša go gatela pele go tšeo ke ikemišeditšego go di...           nso  Sepedi (Northern Sotho)

======================================================================
  Language: Sesotho (sot)
======================================================================

                                                                                                                      text language_code language_name
0  Ha re bolokaneng\n\nvukuzenzele unnamed\n\nNaha ya bo rona e se e fetetse mo hatong wa bobedi wa tlhokomediso karabe...           sot       Sesotho
1  Sena se tlile e le kimollo ho maAfrika Borwa ka ofela a neng a tshwanela ho phela tlasa dithibelo tse matla bakeng s...           sot       Sesotho
2  Ke letshwao la kgatelopele eo re e etsang mabapi le ho fokotsa ditshwaetso tse ntjha le boima hodima ditsha tsa rona...           sot       Sesotho
3                             E boetse ke ntshetsopele ya bohlokwa jwaloka ha re tsitlallela ho qala botjha moruo wa rona.           sot       Sesotho
4                                                                                  Feela e sa le hoseng hore re ka keteka.           sot       Sesotho
5  Re ntse re le mahareng haholo a sewa sena se bolayang se seng se fetile ka maphelo a fetang 11 000 ka hara Afrika Bo...           sot       Sesotho
6  Re iphumana re na le di tlaleho tse etsang halofo ya milione tse tiiseditsweng, re ntse re na le ditshwaetso tse mae...           sot       Sesotho
7                                                            Ho ntse ho na le monyetla wa hore lefu lena le ropohe botjha.           sot       Sesotho
8  Haeba re batla se re hopo tsang ka botlalo hore re lokele ho fadimeha, ke hore re shebe se etsahetseng dikilomithara...           sot       Sesotho
9  Dikgwedi tse tharo esale naha eo e tsebahatsa hore ha e sa na kokwanahloko ya corona , New Zealand e boetse e hlaset...           sot       Sesotho

======================================================================
  Language: siSwati (ssw)
======================================================================

                                                                                                                      text language_code language_name
0  I-NSFAS yaphumelelisa emaphupho ami\n\nMore Matshediso \n\nSikimu Savelonkhe Sekusita Titjudeni Ngetimali (NSFAS) si...           ssw       siSwati
1  Mashego waseSebokeng eGauteng endzaweni yaseVaal utsi bekangeke akhone kukhokhela imali yekufundza naletinye ti ndle...           ssw       siSwati
2  “Kwengeta, imali lengiyi tfola njalo ngenyanga levela ku-NSFAS ingenta ngi khone kulala futsi ngi fundze ngisutsi,” ...           ssw       siSwati
3                       Mashego ungumfundzi lowenta umnyaka wesitsa tfu kutifundvo tebunjiniye la eNyunivesi yasePretoria.           ssw       siSwati
4                                                                                    “Tindleko tekufundza tibi ta kakhulu.           ssw       siSwati
5  Kuletifundvo lengitikhetsile, ecinisweni bengingeke ngikhone kukhokhela tinyanga letisitfupha, angisakhulumi ngemnya...           ssw       siSwati
6  Mashego watfola mati kuletjeni ngemnyaka we2016 futsi bekamfundzi lowaphuma embili eklasini lakhe, kodvwa angenayo i...           ssw       siSwati
7                                       Sicelo sakhe selusito lwetimali ku-NSFAS saphumelela ngemnyaka wekufundza we-2018.           ssw       siSwati
8                                        “Loku kwanginika litfuba lekuphumelelisa liphupho lami lekufundzela bunji niyela.           ssw       siSwati
9  Imfundvo idlala indzima lenkhulu ekuti tfutfukiseni futsi iyangisita kutsi ngichubekele embili kuko konkhe bengifisa...           ssw       siSwati

======================================================================
  Language: Xitsonga (tso)
======================================================================

                                                                                                                      text language_code language_name
0  NSFAS yi tiyisisa milorho ya mina\n\nMore Matshediso \n\nXikimi xa Tiko xa Mali ya Mphalalo wa Machudeni  (NSFAS) xi...           tso      Xitsonga
1  Mashego wa le Sebokeng eGauteng endhawini ya Vaal u vula leswaku a tava a nga kotanga ku fikelela tihakelo ta xikolo...           tso      Xitsonga
2  “Ku tatisa, mpimo lowu nyikiwaka hi n'hweti lowu ndzi wu kumaka kusuka eka NSFAS wu endla leswaku ndzi etlela ndzi d...           tso      Xitsonga
3   Mashego i xichudeni xa lembe ra vunharhu lexi xi dyondzelaka digiri ya vuinjhiniyara bya vuako eYunivhesiti ya Pitori.           tso      Xitsonga
4                                                                                    “Tihakelo ta xikolo ta durha swinene.           tso      Xitsonga
5  Khoso leyi ni nga yi hlawula, a ni nga ta fikelela ku hakelela simesita, ni ngaha vuli lembe rin'we ra dyondzo ,” a ...           tso      Xitsonga
6  Mashego u pasile ntangha khume hi 2016 naswona a ri mudyondzi wa le henhla etlilasini ya yena, kambe a ngari na ndle...           tso      Xitsonga
7                      U endlile xikombelo xa nseketelo wa tihakelo kusuka eka NSFAS a humelela eka lembedyo ndzo ra 2018.           tso      Xitsonga
8                                              “Leswi swi ndzi nyikile nkarhi wo endla leswaku norho wa mina wu hume lela.           tso      Xitsonga
9  Dyondzo yi tlanga xiphemu xikulukumba eka ku antswa ka mina na swona yi ndzi pfuna ku ya emahlweni eka hinkwaswo les...           tso      Xitsonga

======================================================================
  Language: Setswana (tsn)
======================================================================

                                                                                                                      text language_code language_name
0  Tla re babalelaneng\n\nvukuzenzele unnamed\n\nNaga ya rona e tsene mo kgatong ya bobedi ya go sa magana le leroborob...           tsn      Setswana
1  Seno se rotse boima jo maAforikaBorwa otlhe a neng a bo rwele jwa go tshelela ka fa tlase ga dikiletso tse di boima ...           tsn      Setswana
2  Seno ke sesupo sa kgate lopele e re e dirang mo go fokotseng palo ya ditshwae tso tse dintšhwa le go fokotsa motlalo...           tsn      Setswana
3                              E bile gape ke selo sa botlho kwa thata jaaka re leka go ka simolola sešwa ikonomi ya rona.           tsn      Setswana
4                                                                                 Fela  go santse go le gale go ka keteka.           tsn      Setswana
5  Re santse re le ka fa ganong la leroborobo le le setlhogo le le setseng ga jaana le komedi tse matshelo a maAforika ...           tsn      Setswana
6  Le fa re na le palo e e fetang halofo ya milione ya batho ba go totobaditsweng fa ba tshwaetsegile, re santse re na ...           tsn      Setswana
7                                            E bile go santse go na le kgona galo ya gore bolwetse jono bo ka ipoa sebedi.           tsn      Setswana
8  Fa e le gore re tlhoka sega kolodi gore re ntshe matlho dinameng, ga re tlhoke go leba kae, re ka lebelela ditiragal...           tsn      Setswana
9  Morago fela ga dikgwedi di le tharo fa e sale go twe naga ga e sa na dikgetse tsa bao ba nang le mogare wa corona , ...           tsn      Setswana

======================================================================
  Language: Tshivenda (ven)
======================================================================

                                                                                                                      text language_code language_name
0  Kha ri tsireledzane\n\nvukuzenzele unnamed\n\nShango ḽashu ḽo ya kha ḽeveḽe ya vhu vhili (2) kha nndwa  yashu na dwa...           ven     Tshivenda
1  Hezwi zwo ḓa sa u femuluwa kha vhathu vhoṱhe vha Afrika Tshipembe vhe vha tshi la fhasi ha nyiledzo dzo khwaṱhaho kh...           ven     Tshivenda
2                                                                     Fhedzi hu kha ḓi vha ma tsheloni kha uri ri pembele.           ven     Tshivenda
3          Ri kha ḓi tou vha vhukati ha dwadze tshifu ḽe ḽa dzhia matshilo a paḓaho 11,000 kha ḽa Afrika Tshipembe fhedzi.           ven     Tshivenda
4  Kha vhathu vho khwaṱhisedzwaho uri vho kavhiwa, vha paḓaho hafu ya miḽioni, ri kha ḓi vha na tshivhalo tsha vho kavh...           ven     Tshivenda
5                                                 Nahone hu na khonadzeo ya tshikhala tsha u nga gonya ha tshivhalo itshi.           ven     Tshivenda
6  Arali ri tshi ṱoḓa tsivhudzo nga ha ṱhoḓea ya u dzula ro fhaṱuwa, ri tea u sedza kha zwithu zwo iteaho zwene zwino f...           ven     Tshivenda
7  Kha miṅwedzi miraru musi shango ḽo ḓivhadzwa uri a ḽi tshe na tshitzhili tsha corona , New Zealand zwa zwino ḽo vhuy...           ven     Tshivenda
8  Naho ṱhaho ya vhulwadze ya zwenezwino ho vha hu vhathu vho kavhiwaho vha si gathi, muvhuso nga u ṱavhanya wo vhuisa ...           ven     Tshivenda
9  Nyiledzo dzi fanaho na dza mathomo dzo dovha dza vhuedzedzwa kha zwipiḓa zwo fhambanaho zwa Europe saizwi vha tshi k...           ven     Tshivenda

======================================================================
  Language: isiXhosa (xho)
======================================================================

                                                                                                                      text language_code language_name
0  U-NSFAS ufezekise amaphupha wam\n\nMore Matshediso \n\nISkimu soNcedo  lwezeZimali sa Bafundi seSizwe  (u-NSFAS) siw...           xho      isiXhosa
1        “Ukongeza apho, isibo nelelo senyanga nenyanga endisifumana ku-NSFAS sindenza ndilale ndifunde ndihluthi,” utsho.           xho      isiXhosa
2  UMashego ngumfundi wonyaka wesithathu ofu ndela isidanga sezobunjineli bokwakha iindlela nee bhulorho kwiDyunivesith...           xho      isiXhosa
3  Kwesi sifundo ndisikhethileyo, ngokwe nyani bendingakwazi uku hlawula imali yesiqingatha nje sonyaka wokufunda, andi...           xho      isiXhosa
4  UMashego uphumelele imatriki ngowama-2016 kwaye ube ngoyena mfu ndi uphambili kwigumbi lakhe lokufunda, kodwa engena...           xho      isiXhosa
5                                      Ufake isicelo senkxaso-mali ngokuyimpumelelo kuNSFAS sonyaka wokufunda wowama-2018.           xho      isiXhosa
6                        “Oku kundinike ithuba lokwenza ukuba iphupha lam lokwenza izifundo zobunjineli libe yimpume lelo.           xho      isiXhosa
7  Imfundo idlala indima enkulu ekuphuhleni kwam njengomntu kwaye iyandi nceda ndiqhubele phambili kuko konke endinqwen...           xho      isiXhosa
8  Ngaphezu kwa -ko konke, indinika amandla okuxhobisa abanye abantu kuluntu endihlala nalo ize ngolo hlobo elo ibe lig...           xho      isiXhosa
9  “Ndibongoza abantu aba tsha ukuba bafake izicelo kwinkxaso-mali ka-NSFAS kuba ukulandela amaphu pha wakho asingumseb...           xho      isiXhosa

======================================================================
  Language: isiZulu (zul)
======================================================================

                                                                                                                      text language_code language_name
0  I-NSFAS ifeze amaphu pho ami\n\nMore Matshediso \n\nIsikhwama Soxhaso mali Lwabafundi Lu kazwelonke (i-NSFAS) seluye...           zul       isiZulu
1  UMashego odabuka eSebokeng lapha endaweni yase-Gauteng e-Vaal uthi ubengeke akwazi ukuzi khokhela imali yokufunda ka...           zul       isiZulu
2  “Ukwengeza kulokhu, imali yokuphila yenyanga nenya nga engiyithola ku-NSFAS ingenza ngikwazi ukufunda futhi ukulala ...           zul       isiZulu
3  UMashego ungumfundi owenza unyaka wesithathu eziqwini zakhe zobunjiniyela kwezokwakha imigwaqo namabhuloho i-civil e...           zul       isiZulu
4  Ngokomkha kha engiwukhethile, bengi ngeke ngikwazi ukukhokhela ngisho imali yokufunda izi nyanga eziyisithupha, ngi ...           zul       isiZulu
5  UMashego uphothule umatikuletsheni wakhe ngonyaka wezi-2016 futhi wabashaya bonke emakha nda abafundi ayefunda nabo ...           zul       isiZulu
6                     Waye wafaka ngempu melelo isicelo soxhasomali luka-NSFAS ukuze axhaseke ngonyaka wokufunda wezi2018.           zul       isiZulu
7         “Lokhu kwanginika  ithuba lokuba ngikwazi ukuthi ngenze amaphupho ami okufundela izifundo zobunjiniyela afezeke.           zul       isiZulu
8  Imfu ndo idlala enkulu indima le ekuthuthukeni kwami futhi mina ingisize ukuthi ngiphumelele kukho konke ebekade ngi...           zul       isiZulu
9  Ngaphezu kwalokho, inginike amandla ukuze ngikwazi ukunika abanye amandla ngokubakhuthaza emphakathini wakithi kanye...           zul       isiZulu

---
## 3. MasakhaNEWS Dataset

**MasakhaNEWS** is a large-scale African news classification dataset built by the Masakhane community.
It contains categorised news articles collected from BBC and VOA news sites across 16 languages
(14 African), covering topics such as politics, health, sports, entertainment, and technology.

- **Source:** [`masakhane-io/masakhane-news`](https://github.com/masakhane-io/masakhane-news) on GitHub
- **Languages loaded:** Amharic, Hausa, Igbo, Oromo, Nigerian Pidgin, chiShona, Somali, Swahili, Tigrinya, isiXhosa, Yoruba
- **Splits:** train / dev / test per language
- **Columns used:** `headline` and `text` (article body)
- **Role in this project:** Source of *human-written* formal news text — chiShona is specifically sourced from here

In [ ]:
# ── Clone MasakhaNEWS from GitHub ─────────────────────────────────────────
REPO_URL  = "https://github.com/masakhane-io/masakhane-news.git"
LOCAL_DIR = "masakhane-news"

if os.path.isdir(LOCAL_DIR):
    print("Repository exists. Updating...")
    subprocess.run(["git", "-C", LOCAL_DIR, "pull", "origin", "main"], check=True)
else:
    print("Repository not found. Cloning...")
    subprocess.run(["git", "clone", REPO_URL, "--depth=1", "-q"], check=True)

# ── Languages available in MasakhaNEWS ───────────────────────────────────
MASAKHANE_LANGUAGES = {
    'amh': 'Amharic',
    'hau': 'Hausa',
    'ibo': 'Igbo',
    'orm': 'Oromo',
    'pcm': 'Nigerian Pidgin',
    'sna': 'chiShona',
    'som': 'Somali',
    'swa': 'Swahili',
    'tir': 'Tigrinya',
    'xho': 'isiXhosa',
    'yor': 'Yoruba',
}

masakhane_dfs = {}
print("\nLoading MasakhaNEWS dataset...\n")

for lang_code, lang_name in MASAKHANE_LANGUAGES.items():
    try:
        splits = []
        for split in ['train', 'dev', 'test']:
            fp = f"{LOCAL_DIR}/data/{lang_code}/{split}.tsv"
            if os.path.exists(fp):
                df_split = pd.read_csv(fp, sep='\t', header=0,
                                       usecols=['headline', 'text'],
                                       on_bad_lines='skip')
                splits.append(df_split)
        if not splits:
            raise FileNotFoundError("No split files found")
        lang_df = pd.concat(splits, ignore_index=True)
        lang_df['language_code'] = lang_code
        lang_df['language_name'] = lang_name
        masakhane_dfs[lang_code] = lang_df
        print(f"  [OK]   {lang_code}  —  {len(lang_df):,} rows")
    except Exception:
        print(f"  [SKIP] {lang_code}  —  not available")

masakhane_df = pd.concat(masakhane_dfs.values(), ignore_index=True) if masakhane_dfs else pd.DataFrame()
print(f"\n  Total rows loaded: {len(masakhane_df):,}")

Repository not found. Cloning...

Loading MasakhaNEWS dataset...

  [OK]   amh  —  1,875 rows
  [OK]   hau  —  3,173 rows
  [OK]   ibo  —  1,940 rows
  [OK]   orm  —  1,615 rows
  [OK]   pcm  —  1,517 rows
  [OK]   sna  —  1,842 rows
  [OK]   som  —  1,463 rows
  [OK]   swa  —  2,371 rows
  [OK]   tir  —  1,356 rows
  [OK]   xho  —  1,476 rows
  [OK]   yor  —  2,050 rows

  Total rows loaded: 20,678

### 3.1 Languages and Line Counts

In [ ]:
masakhane_summary = (
    masakhane_df
    .groupby(['language_code', 'language_name'])
    .size()
    .reset_index(name='num_lines')
    .rename(columns={
        'language_code': 'Language Code',
        'language_name': 'Language',
        'num_lines':     'Number of Lines'
    })
    .sort_values('Number of Lines', ascending=False)
    .reset_index(drop=True)
)

print(f"MasakhaNEWS — {len(masakhane_summary)} languages loaded\n")
display(masakhane_summary)

MasakhaNEWS — 11 languages loaded

   Language Code         Language  Number of Lines
0            hau            Hausa             3173
1            swa          Swahili             2371
2            yor           Yoruba             2050
3            ibo             Igbo             1940
4            amh          Amharic             1875
5            sna         chiShona             1842
6            orm            Oromo             1615
7            pcm  Nigerian Pidgin             1517
8            xho         isiXhosa             1476
9            som           Somali             1463
10           tir         Tigrinya             1356

### 3.2 Columns and First 5 Rows per Language

In [ ]:
print("\nMasakhaNEWS columns:", masakhane_df.columns.tolist())
print()

for lang_code, lang_name in MASAKHANE_LANGUAGES.items():
    if lang_code not in masakhane_dfs:
        continue
    print(f"{'='*70}")
    print(f"  Language: {lang_name} ({lang_code})")
    print(f"{'='*70}")
    display(masakhane_dfs[lang_code].head(10))
    print()

MasakhaNEWS columns: ['headline', 'text', 'language_code', 'language_name']

======================================================================
  Language: Amharic (amh)
======================================================================

                                             headline                                                                                                                     text language_code language_name
0    የስፖርት ኮከቦች እና የንግድ ምልክቶቻቸው- ከቦልት እስከ ክርስቲያኖ ሮናልዶ  የአትሌቲክሱ ዓለም ኮከብ እና ፈጣኑ ሰው ዩሴን ቦልት ከውድድር በፊት እና በኋላ የሚያሳየውን ታዋቂ የሆነውን ምልክት ለንግድ ምልክትነት ለመጠቀም ጥያቄ በማቅረብ ላይ ይገኛል። እሱ ብቻ...           amh       Amharic
1           እግር ኳስ፡ ዩናይትድ፣ አርሴናል፣ ቼልሲ . . . ምን አስበዋል?  የስፖርት ጋዜጦች ስለ እግር ኳስ ምን እያሉ ነው? በሚቀጥለው ጥር የሚከፈተው የዝውውር መስኮትስ ምን ያሳየን ይሆን?ዋና ዋናዎቹን በዚሀች አጭር ዘገባ እንዳስሳለን። አላንድ፡ የቦሩሲያ ...           amh       Amharic
2                ዓለምን ካስጨነቃት የዋጋ ንረት ተጠቃሚዎቹ እነማን ናቸው?  ከኮሮናቫይረስ ወረርሽኝ ተጽእኖ ሳያገግም የዩክሬን እና ሩሲያ ጦርነት የገጠመው የዓለም ምጣኔ ሃብት ከቀውስ አዙሪት ውስጥ አልወጣም። የነዳጅ እና የምግብ ምርቶች የዋጋ ንረት በመላው ዓ...           amh       Amharic
3           ኮሮናቫይረስ፡ በቫይረሱ የሞቱት የሮማኒያው ከንቲባ በምርጫ አሸነፉ  በኮሮናቫይረስ የሞቱት የሮማኒያው ከንቲባ በቅርቡ የተደረገውን ምርጫ በከፍተኛ ድምፅ አሸንፈዋል። 64 በመቶ የመራጮችንም ድምፅ ማግኘት ችለዋል። በደቡባዊቷ ሮማኒያ በምትገኘው ግዛት ዴቬ...           amh       Amharic
4         ኮሮናቫይረስ፡ አውሮፕላኖች እንዴት ነው በፀረ- ተህዋሲያን የሚፀዱት?  የኮሮናቫይረስ ወረርሽኝ መከሰቱን ተከትሎ  ቀጥ ብሎ የነበረውን የአለም የንግድ እንቅስቃሴን ለመመለስ በርካታ ጥረቶች እየተደረገ ነው። በተለያዩ አገራትም የቫይረሱን ስርጭት ለመግታት ጥ...           amh       Amharic
5                         ቤኒቶ ሙሶሊኒ ላይ የተኮሰችው አየርላንዳዊት  ጊዜው በፈረንጆቹ ሚያዝያ 7 1926 ነበር። ቦታው ደግሞ የጣልያኗ መዲና ሮም። የሃገሬው ሰው በ20ኛው ክፍለ ዘመን ከነበሩ ኃያላን መካከል አንዱ የነበረውን ግለሰብ ለማየት ተኮልኩሏል።...           amh       Amharic
6                        ኮሮናቫይረስና የነዳጅ ዘይት ምን አገናኛቸው?  ኮሮናቫይረስ የማይነካው ነገር እንደሌለ እየታየ ነው። በየሰበብ አስባቡ እያሻቀበ የነበረውን ነዳጅ ዘይትን ሊነካው ዳርዳር እያለ ነው። በሽታው አሳሳቢ ደረጃ ላይ በደረሰበት በአሁኑ ጊዜ...           amh       Amharic
7   በርካታ ኢትዮጵያውያን የሚጠበቁበት የቤልግሬዱ የቤት ውስጥ አትሌቲክስ ሻምፒዮና  ሰርቢያ ቤልግሬድ ውስጥ ዛሬ ከመጋቢት 9 ተጀምሮ አስከ 11/2014 ዓ.ም በሚቆየው የዓለም የቤት ውስጥ የአትሌቲክስ ሻምፒዮና አፍሪካዊያን አትሌቶች ሜዳሊያ ያገኛሉ ተብሎ ይጠበቃል። ኬ...           amh       Amharic
8  ምርጫ 2013፡ የምርጫ ውጤት በምርጫ ክልል ደረጃ ረቡዕና ሐሙስ ይገለጻል ተባለ  ሰኞ ዕለት የተካሄደው ምርጫ ውጤት በምርጫ ክልል ደረጃ ረቡዕና ሐሙስ ይፋ እንደሚደረግ የኢትዮጵያ ብሔራዊ የምርጫ ቦርድ አስታወቀ። ቆጠራ በተጠናቀቀባቸው ምርጫ ጣቢዎች ውጤቶች ከማክሰኞ...           amh       Amharic
9          በኒው ዚላንድ ሰዎች በፍቃዳቸው እንዲሞቱ የሚደነግግ ሕግ ሊወጣ ነው  በኒው ዚላንድ በጠና የታመሙ ሰዎች በፍቃዳቸው እንዲሞቱ የሚደነግግ ሕግ ሊወጣ ነው። ባለፈው ወር በተካሄደ ሕዝበ ውሳኔ 65.2% መራጮች የፍቃድ ሞትን ደግፈዋል። ዩትኔዝያ ወይም የፈቃድ...           amh       Amharic

======================================================================
  Language: Hausa (hau)
======================================================================

                                                                       headline                                                                                                                     text language_code language_name
0                   Yadda Shugaban Kungiyar Kirista ya gina masallaci a Adamawa  A wani abu da ba a saba gani ba a ƙasa irin Najeriya, wani malamin addinin kirista ya gina masallaci ga wasu 'yan gu...           hau         Hausa
1                  Burina na zama hamshakiyar 'yar kasuwa – Rayya Kwana Casa'in  Tauraruwar fina-finan Hausa Surayya Aminu wacce aka fi sani da Rayya a cikin shirin talabijin na Kwana Casa'in na ta...           hau         Hausa
2  Ƙoƙarin da muke yi na haƙo man fetur a Gombe da Bauchi - Gwamna Inuwa Yahaya  Shirin Gane Mini Hanya na wannan makon ya tattauna da Gwamnan Gombe Muhammadu Inuwa Yahaya game da shirinsu na haƙo ...           hau         Hausa
3                                             Yadda kyanda ke barazana a duniya  Sama da mutum 140,000 suka mutu sakamakon cutar kyanda a bara, yayin da adadin wadanda ke fama da cutar ke karuwa a ...           hau         Hausa
4              Babangida Aliyu: 'Yan Najeriya na kewar shekaru 16 na mulkin PDP  Tsohon gwamnan Jihar Neja da ke arewacin Najeriya ya ce 'yan kasar suna kewar mulkin jam'iyyar PDP na tsawon shekara...           hau         Hausa
5     Coronavirus: Cutar ta hana marasa lafiya miliyan 2 zuwa asibiti a Nigeria  Ministan Lafiya na Najeriya ya ce kimanain kashi 50 cikin 100 na marasa lafiya masu zuwa asibitoci a duba su sun dai...           hau         Hausa
6                               Mece ce cutar kyandar biri, kuma me ke jawo ta?  An samu ɓullar cutar ƙyandar biri a Birtaniya a jikin wani mutum da ya je ƙasar kwanan nan daga Najeriya. A wannan m...           hau         Hausa
7                  Cikin hotuna: Sarauniyar Ingila ta yi shekara 70 a kan mulki  Sarauniya Izabel ta Ingila ta cika shekara 70 a kan karagar mulki, kuma hakan ya sa ta zamo ta farko da ta yi wannan...           hau         Hausa
8                      Amurka za ta janye soja 1,000 daga Syria saboda Turkiyya  Amurka tana yunkurin janye sojojinta 1,000 daga Arewacin Syria yayin da Turkiyya ke kara matsa kaimin hare-haren da ...           hau         Hausa
9                    Hotunan Afirka na mako: Daga 4 zuwa 10 ga watan Maris 2022             Zababbun hotunan Afirka da 'yan nahiyar a wasu nahiyoyi a wannan mako: Dukkanin hotuna na da hakkin mallaka.           hau         Hausa

======================================================================
  Language: Igbo (ibo)
======================================================================

                                                                                            headline                                                                                                                     text language_code language_name
0                                Miyetti Allah: 'Anyị ga-agbachi ụlọahịa anyị niile n'Enugwu steeti'  Ngalaba na-ahụ maka ọzụzụ nama bụ Miyetti Allah ekwuola na ha ga-agbachi ụlọahịa niile n'Enugwu n'ụbọchị iri na anọ ...           ibo          Igbo
1                       'Biafra na-enye anyị ohere ihe anyị nwereike ịbụ' - Ọkaikpe Nkemdilim Izuako  Okwu inweta Biafra bụ nke na-ewu ewu kamgbe ebe ọtụtụ ndị Igbo ọkachasị ndị ntoroọbịa na-ekwu ka e mee refarandum. O...           ibo          Igbo
2                                                         Arsenal vs Lyon: Ekwe akụọla Arsenal n'isi  Moussa Dembele ji goolu abụọ gbarie ndị Arsenal obi ka ha zutere ịzọ Iko Emirates. Na Pierre-Emerick Aubameyang nyer...           ibo          Igbo
3                                  Nigerian Celebrities: Lekwa ihe mere ka ndị a ama ama wuo n'ízu a  Dịka izuụka a na-abịa n'isi njedebe, anyị na-ewetara gị ihe ndị ama ama ụfọdụ mere nke dara ụda. DAVIDO Obi bụ David...           ibo          Igbo
4  Ghana Election 2020: Ndị pati mgbagha mba Gana ajụla mpụtara ntuliaka nyere Nana Akufo-Addo mmeri  Pati anọghị na gọọmentị mba Gana bụ ndị isi mgbagha ajụla mpụtara ndị ọrụ ntụlịaka ha nụ Ghana Electoral Commission ...           ibo          Igbo
5                                            Imo Bride Price: Ihe ọ na-ewe iji lụọ nwaanyị na Mbaise  Mbaise bụ okpuruọchịchị a ma ama n'Imo steeti n'ala Igbo. Mana ugbua, ọ bụ ihe ọzọ mere ka ha bụrụ okwu a kpụ n'ọnụ ...           ibo          Igbo
6                            Coronavirus in Nigeria: Mmadụ ise ọhụrụ ebutela coronavirus na Naịjirịa  Mmadụ ise ọhụrụ ebutela ọrịa coronavirus na Naịjirịa. Ngalaba mgbochi ọrịa bụ 'National Centre for Disease Control' ...           ibo          Igbo
7                                                        Victor Moses enyeela goolu mbu ya na Turkey  Akụkọ dị mkpa Nwaafọ Naịjirịa na-agba bọọlụ na mba ofesi bụ Victor Moses jị ọkpụ goolu gwa ndị Turkey na ya abịara. ...           ibo          Igbo
8               Frank Ibezim: E duola ya n'iyi ọrụ dịka onye nnọchiteanya Imo North n'ụlọomeiwu ukwu  Onyeisi ụlọomeiwu ukwu bụ Ahmad Lawan eduola Chukwuma Frank Ibezim n'iyi ọrụ dịka onye omeiwu na-anọchite anya Imo N...           ibo          Igbo
9                                 Miyetti Allah: Ihe mere ha ji bụrụ okwu akpụ n'ọnụ na soshal midia  Akụkọ ndị kachasị mkpa taa: Otu Miyetti Allah akpala agụ aka n'ọdụ. Ụmụ Naijiria na-ewere ha iwe maka okwu otu onyei...           ibo          Igbo

======================================================================
  Language: Oromo (orm)
======================================================================

                                                                                                        headline                                                                                                                     text language_code language_name
0                                  Maashinni kitaaba akka sagalee nama barreesseetti ol fuudhee dubbisu kalaqame  Chaayinaatti toorri ittiin interneeta barbaaddatanii (search engine) Sogou jedhamu Artifishaal Intelijensii (AI) akk...           orm         Oromo
1                            Baalandoor: Liyooneel Mesiin badhaasa Taphataa cimaa Addunyaa marroo 7ffaa injifate  Taphataan sarara fuulduraa Paariis Seent Jermen fi Arjentiinaa Liyooneel Mesiin Badhaasa Balandoor marsaa 7ffaadhaaf...           orm         Oromo
2                                              'Seeqaan aangoo dabarsa, hoogganaan koo garuu Baabaa dha'-Uhuuruu  Pireezidantiin Keeniyaa waggoota sagal darbanii Uhuuruu Keeniyaattaa pireezidantii haaraa baallii fudhachaa jiran Wi...           orm         Oromo
3                                Hospitaalli fardaa Bishooftuutti baname tajaajila baqaqsanii yaaluu kennaa jira  Hospitaalli fardaa Itoophiyaatti kan jalqabaati jedhame Bishooftuutti hundeeffame fardeen dhukkubsataniif tajaajila ...           orm         Oromo
4  Shamarreen Iraan dirree kubbaa miilaa seente jedhamuun himatamte abidda ofitti qabsiisuun lubbuun ishee darbe  Deeggartuun kubbaa miilaa Iraan torbee dura mana murtuu fuulduratti abidda ofitti qabsiifte lubbuun ishee darbe. Sha...           orm         Oromo
5                             Hoogganaan mormituu Raashiyaa ''suummeffame'' wal’aansaaf gara Jarmanitti geeffame  Namni Puutiiniin mormuun beekaman kun akka deeggartoonni isaa jedhanitti shayee summa’e dhuguun kan of-wallaalan yoo...           orm         Oromo
6                                         Ispoortii: Mesin galii argatuun taphattoota kaan caalee tokkoffaa ta'e  Jifataan Baarseloonaa Liyoonel Meesin bara 2020 taphattoota galii guddaa argatan keessaa kan duraa ta'e. Barruun gal...           orm         Oromo
7                          Mootummaan Keeniyaa rakkoo nageenyaa Bulchiinsa Marsabiit furuuf humna addaa bobbaase  Mootummaan Keeniyaa rakkoo nageenyaa Bulchiinsa Marsabiit furuuf poolisii dabalatee, humnoota addaa kumaatamatti lak...           orm         Oromo
8                                             Chaayinaan faana USSR fi USA hordofuun Addeessarraa dhagaa fiduufi  Erga bara 1970'oota as yeroo jalqabaaf Chaayinaan Addeessa yookiin ji'arraa dhagaa fiduufi. Xiyyaarri 'Chang'e-5' je...           orm         Oromo
9                                           Itoophiyaan hiree waancaa Afrikaa 2022 irratti hirmaachuu bal'ifatte  Gareen kubbaa miilaa biyyaalessaa Itoophiyaa tapha kaleessa Madagaaskaar waliin taphate irratti goolii afur galchuun...           orm         Oromo

======================================================================
  Language: Nigerian Pidgin (pcm)
======================================================================

                                                                                                                  headline                                                                                                                     text language_code    language_name
0                                       Maduka Okoye: How Super Eagles goalkeeper become centre of attention for Nigerians  "I no fit wait to see Maduka Okoye on top my screen today," dis na comment wey one of di female fans of di Super Eag...           pcm  Nigerian Pidgin
1                                     Grammys 2020: Burna Boy, Angelique and oda tins wey pipo dey watch out for dis night  Di 62nd annual Grammy Awards go happun for Los Angeles on Sunday night, January 26. Dem dey call am "music biggest n...           pcm  Nigerian Pidgin
2                                                Ayo Makun: AY Comedian and wife Mabel born dia second pikin afta 13 years  Nigeria comedian and feem maker, Richard Ayodeji Makun, wey pipo sabi as AY Comedian and im wife, Mabel don born dia...           pcm  Nigerian Pidgin
3                                               Footballer wey bite im opponent penis for match chop five years suspension  One player chop five years suspension for France sake of say im bite im opponent penis for fight wey happun afta dia...           pcm  Nigerian Pidgin
4                                                                     Breakdown of matchday six games for Champions League  Twelve teams don qualify for di round of 16 for Champions League so far. E mean say four teams go book dia place for...           pcm  Nigerian Pidgin
5                                 Ghana vs Nigeria play off: Super Eagles squad arrive Kumasi to clash Black Stars - Fotos  Super Eagles of Nigeria arrive Kumasi for de first leg of de 2022 FIFA World Qualifier play offs against Ghana  on F...           pcm  Nigerian Pidgin
6                                BBNaija S6: Queen fight Whitemoney sake of Jackie B for Big Brother Naija 'Shine Ya Eyes'  Di tension between Big Brother Naija housemates Queen and Whitemoney reach anoda level on Friday afta dia gbos-gbos ...           pcm  Nigerian Pidgin
7  Non- Career Ambassador: Nigeria President Buhari do appoint 41 non-career ambassadors - See wetin you need to know a...  Nigeria President Muhammadu Buhari approve di renewal of di appointments of 12 non-career ambassadors and promise sa...           pcm  Nigerian Pidgin
8                                   Big Brother Naija 2021 housemates: Africa Magic reveal BBNaija Shine Ya Eye housemates  Di 2021 edition of di biggest reality TV show for Nigeria, Big Brother Nigeria don officially start. According to di...           pcm  Nigerian Pidgin
9                    BBNaija: Erica and Kidd 'ship' for Big Brother Naija show dey make fans heart cut - See di reason why  Fans of Big Brother Naija dey react to Kiddwaya and Erica relationship afta she tell am say make dem continue as fri...           pcm  Nigerian Pidgin

======================================================================
  Language: chiShona (sna)
======================================================================

                                                                             headline                                                                                                                     text language_code language_name
0                                              ‘Tagadzirira’ . . . bhora ngaritambwe.    KUCHANGE kusingadanwe anonzwa svondo rino kunhandare dzinosanganisira National Sports Stadium muHarare, Mandava St...           sna      chiShona
1                                                     Nhabvu yevechidiki yosimudzirwa    SHASHA dzakambonetsa munhabvu – Godfrey ‘Goda’ Moyo naBeavan Chikaka – vobatana mukusimudzira vatambi vechidiki iz...           sna      chiShona
2  Nyanzvi dzeHutano Dzofara neKusashaya kweVanhu neCovid-19 muMazuva Manomwe Adarika  Bazi rezvehutano rakazivisa nemusi weChina kuti huwandu hwevanhu vafa nechirwere cheCovid-19 hwaramba huri pamazana ...           sna      chiShona
3                       Dambudziko Rekushaya Mari muMabhanga Roenderera Mberi muNyika  Nyazvi munyaya dzezvehupfumi uye vanhuwo zvavo munyika vari kushora zvikuru vemabhanga uye vemuzvitoro nekuvabhadhar...           sna      chiShona
4                Kambani yeKwese TV Inopihwa Rezenisi Kuti Itepfenyure paDandemutande  Sangano reZimbabwe Institute of Southern Africa-Zimbabwe rinoti rinotambira nemufaro kupihwa kwemarezenisi matatu ek...           sna      chiShona
5                   VaMangudya Vokurudzirwa Kuzadzikisa Zvavanotaura paKufambisa Mari  Gavhuna weReserve Bank of Zimbabwe, VaJohn Mangudy,a neChishanu vakaparura hurongwa hwavo hwepagore hwekushandiswa k...           sna      chiShona
6                             Zimbabwe Inovharwa kweMasvondo Matatu Kutanga neMuvhuro  Zimbabwe inoti ichange isingachabvumidze vanhu kubuda mudzimba dzavo kutanga nemusi weMuvhuro senzira yekuyedza kumi...           sna      chiShona
7                                                            Zim ine tarenda: Songani     MUTAMBI wemaWarriors neVestri yekuIceland — Silas Songani — anoti vatambi vemuZimbabwe vane tarenda rinonwisa mvu...           sna      chiShona
8                Vakawanda muNyika Voisa Tarisiro paHurumende Ichaumbwa naVaMnangagwa  Vanhu vakawanda vanoti vane tarisiro yekuti zvinhu zvichanaka nekukurumidza munyika zvichitevera kugadzwa kwakaitwa ...           sna      chiShona
9                                Kanzuru yeChinhoyi Yotsamwisa Vatyairi veDzimotokari  Vazhinji vataura neStudio7 muChinhoyi vanoti nguva dzakawanda vanosungirwa kusapaka motokari zvakanaka vachiti panen...           sna      chiShona

======================================================================
  Language: Somali (som)
======================================================================

                                                                                      headline                                                                                                                     text language_code language_name
0       Mareykanka dad ka badan 40 qof oo tahriibayaal ah oo Meydadkooda laga dhex helay Gaari  Ugu yaraan  46 qof oo la rumeysan yahay in ay yihiin dad muhaajiriin ah ayaa meydkooda laga dhex helay gaari ah nooc...           som        Somali
1    Warar sheegaya in la sii daayay badmaaxayaashii Turkiga ee lagu afduubtay xeebaha Nigeria  Toban badmaax oo u dhashay dalka Turkiga oo bishii la soo dhaafay laga afduubtay xeebaha Galbeedka Afrika ayaa la si...           som        Somali
2  Doorashada Mareykanka 2020: Dadka Mareykanka oo galay xaalad ay ku tilmaameen "mid cakiran"  Donald Trump ayaa muddo isbuucyo ah sheegayay in haddii codadka doorashada ay isku dhawaadaan uu xisbiga kasoo hor j...           som        Somali
3                                Shan arrimood oo ku saabsan isticmaalka khudradda Beytaraafka  Beytaraafka waa khudrad muhiim ah oo ka qeyb qaadata xoojinta caafimaadka qofka isla markaana horseeda in qofka isti...           som        Somali
4               Waxyaabaha u gaarka ah gawaarida qaybta ka ah ilaalada madaxweynaha Mareykanka  Waxyaabaha ay dadku sida aadka ah u xiiseeyaan waxaa ka mid ah arrimaha ku xeeran ilaalada madaxda dunida. Dalka Mar...           som        Somali
5                                   Madaxweynihii hore ee Kenya Daniel Arap Moi oo geeriyooday  Madaxweynaha Kenya, Uhuru Kenyatta oo ku sugan dalka Mareykanka ayaa shaaciyay in uu geeriyooday Madaxweynihii hore ...           som        Somali
6                                      Kanaalka Calais: Waa kuwama dadka ku naf-waayay Calais?  Ugu yaraan 27 qof ayaa ku dhimatay musiibadii ugu xumeyd ee soo galootiga ee kanaalka, waxaana saraakiisha Faransiis...           som        Somali
7                        Trump oo lagu dhalillay inuu isbitaalka ka baxay xilli uu hayo Korona  Khuburada caafimaadka ayaa su'aalo iska weydiinayo go'aanka Trump uu uga soo baxay isbitaalka lagu daweynayay si uu ...           som        Somali
8                          Shaqada Malabka: 'Lacag badan baan shaqeynayay, saboolna waan ahaa'  "Lacag ayaan sameynayay, balse ma heysan haddana wax lacag ah," ayuu yiri Scott Davies, aasaasaha shirkada Hilltop H...           som        Somali
9                            Calaamadaha lagu garto kansarka ku dhaca xubinta taranka ee ragga  Hormoonnada shahwada ee ragga ayaa qaabilsan dhinaca dhalmada waxayna kasoo baxaan xubinta taranka ee loo yaqaan xin...           som        Somali

======================================================================
  Language: Swahili (swa)
======================================================================

                                                                                     headline                                                                                                                     text language_code language_name
0  Tetesi za soka Ulaya Jumatatu 26.04.2021: Varane, Camara, Nagelsmann, Willock, Azpilicueta  Chelsea wapo mbele ya  Manchester United na Paris St-Germain katika mbio za kutaka kumsajili beki wa Real Madrid na ...           swa       Swahili
1                                                              Je chanjo ya corona ni salama?  Hospitali za Uingereza zinajiandaa kuanza kutoa dozi za kwanza za chanjo ya virusi vya corona sasa kwasababu wadhibi...           swa       Swahili
2     Matokeo ya uchaguzi Marekani 2020: Donald Trump amfuta kazi Waziri wa Ulinzi Mark Esper  Rais Donald Trump amemfuta kazi Waziri wa  Ulinzi  Mark Esper, na kutangaza kwenye Twitter kwamba afisa huyo  wa nga...           swa       Swahili
3                             Je wajua mwanamke na mwanaume hawapaswi kufanya mazoezi pamoja?  Mazoezi ya asubuhi ya mapema yanatajwa kuwa ni muhimu na yenye afya kwa wanawake wanaotaka kupunguza uzito na kupung...           swa       Swahili
4           Watoto waliolazimika kuwa kimya kuhusu baba zao wakutana na maaskofu jijini Paris  Watoto wa makasisi wa kikatoliki ambao wanahisi  ''kunyamazishwa'' na kanisa kwa miongo kadhaa wataeleza simulizi za...           swa       Swahili
5                                                   T﻿etesi za soka Ulaya Jumapili 06.11.2022  Real Madrid wana wasiwasi kwamba mbinu ya Liverpool kwa kiungo wa kati wa Borussia Dortmund na Uingereza Jude Bellin...           swa       Swahili
6                            Netlicks? Televisheni ambayo unaweza kuonja ladha ya kioo chake’  Mfano wa skrini ya TV "unayoweza kulamba" ambayo inaweza kuwa na ladha ya chakula imetengenezwa na profesa wa Kijapa...           swa       Swahili
7                                              Je unajua mikono yako ni 'hatari' kwa  maisha?  Umuhimu wa kunawa mikono na kuiweka katika hali ya usafi linaweza kuonekana ni jambo la kawaida, na kwa baadhi huend...           swa       Swahili
8       Kifo cha Magufuli:Jinsi Magufuli anakavyokumbukwa katika kijiwe hiki cha kahawa,Geita                                Rais John Magufuli anavyokumbukwa katika kijiwe alichokuwa anakunywa kahawa mkoani Geita.           swa       Swahili
9                     Kasisi asiyetaka 'kumsikitisha' Mungu ajenga kanisa na msikiti Ethiopia  Kasisi mmoja nchini Ethiopia anachangisha fedha za kujenga kanisa na msikiti katika mji uliopo eneo la mashariki la ...           swa       Swahili

======================================================================
  Language: Tigrinya (tir)
======================================================================

                                                         headline                                                                                                                     text language_code language_name
0                       ምዕራባውያን ኣብ ልዕሊ ፕረዚደንት ቭላድሚር ፑቲን እገዳ ኣንቢሮም  ሃገራት ምዕራብ ሩስያ ናብ ዩክረይን ዝፈጸመቶ ወራር ምኽንያት ብምግባር ኣብ ልዕሊ ፕረዚደንት ቭላድሚር ፑቲንን ሚኒስተር ጉዳያት ወጻኢ ሰርጌ ላቭሮቭን እገዳታት ኣንቢሮም። በዚ መሰረት ...           tir      Tigrinya
1                     ቦርድ ትዊተር ንምንታይ'ዩ ኢሎን መስክ ነቲ ትካል ክዕድጎ ዘይደልይ?  ሃብታም ዓለምና ኢሎን መስክ ንትዊተር ብ 43 ቢልዮን ዶላር ንምዝግዛእ ጠለብ ምቕራቡ ስዒቡ፡ ቦርድ እቲ ትካል ኣንጻር ‘ተጻባኢ’ ዝበሎ ዋንነት ምንቅስቓስ ጀሚሩ ኣሎ፡፡ እቲ ቦርድ ንሓ...           tir      Tigrinya
2                                ኢሬቻ 2013፡ ኣከባብራ በዓል ህዝቢ ኦሮሞ ብስእሊ  ዓመታዊ በዓል ኢሬቻ ኣብ ኣዲስ ኣበባ ይኽበር ኣሎ። በሰንኪ ኮሮናቫይረስ ከምቲ ናይ ዝሓለፉ ዓመታት ብዙሕ ህዝቢ ኣብቲ በዓል ከም ዘይዕደም ቀዲሙ ተገሊጹ ነይሩ። እቲ በዓል ጽባሕ ሰንበ...           tir      Tigrinya
3           ኮኾብ ተዋሳኣይ ብላክ ፓንተር፡ ቻድዊክ ቦዝማን ኣብ 43 ዓመቱ ብሕማም መንሽሮ ዓሪፉ  ኣብ ፊልም ብላክ ፓነተር ብዝነበሮ ተሳትፎ ተፈላጥነት ዝረኸበ ኣሜሪካዊ ተዋሳኣይ ቻድዊክ ቦዝማን ኣብ 43 ዓመቱ ብሕማም መንሽሮ ዓሪፉ። ቅድሚ ክልተ ዓመት ዝተዘርግሐት ብላክ ፓንተር ኣ...           tir      Tigrinya
4  ብብኽነት ገንዘብ ዝተነቕፈ ቀዳማይ ሚኒስተር እሰራኤል፡ 'ወጻኢታት ስድራይ ባዕለይ ክኽእል'የ' ኢሉ  ብዙሕ ገንዘብ ኣባኺንካ፡ ዝብል ወቐሳ ዝወረዶ ቀዳማይ ሚኒስተር እሰራኤል ናፍታሊ በነት፡ ወርሓዊ ወጻኢታት ምግቢ ስድራኡ ካብ ጅባኡ ክሽፍን ከምዝወሰነ ኣፍሊጡ። ኣብ ሓደ መደበር ተለቪዥ...           tir      Tigrinya
5           ትማሊ ኣብ ቤት ምኽሪ ጸጥታ ሕቡራት ሃገራት ብዛዕባ ኢትዮጵያ ዝተላዕሉ ቀንዲ ጉዳያት  እቲ ኣብ ዝሓለፈ ዓመት ኣብ ክልል ትግራይ ዝጀመረ ኲናት ኣብዚ ሕጂ እዋን ናብ ጎረባብቲ ክልላት ኣምሓራን ዓፋርን ብምልሓሙ ዓብዪ ሻቕሎትን ሰብኣዊ ቅለውላውን ፈጢሩ ኣሎ። እዚ ዝኸፍአ ...           tir      Tigrinya
6                                          መሰነይታ ንግስቲ ኤልሳቤጥ ዳግማዊት                   ስነ ስርዓት ቀብሪ ንግስቲ ኤልሳቤጥ ዳግማዊት ትማሊ ኣብ ለንደን ተፈጺሙ። ኣብቲ ስነ ስርዓት ቀብሪ መራሕቲ ሃገራት ዝርከብዎም ልዕሊ ክልተ ሽሕ ወከልቲ ተረኺቦም።           tir      Tigrinya
7                         ናይጀሪያዊት ኮኾብ ተዋሳኢት ናጂ፡ ካብ ኖሊዉድ ናብ ኔትፍሊክስ  ናይጀራዊት ኮኾብ ተዋሳኢትን ናይ ፊልም ዳይረክተርን ጀነቪቭ ናጂ ድሮ፡ ዓቢይ ግምት ዝወሃባ ምዃና ዘረጋገጸት ሰብ ብምዃና፡ እቲ ኣብ ኔትፍሊክስ ዝኣተወ ፊልማ ካብ ውድድር ሽልማት ኦስካ...           tir      Tigrinya
8          ወርሒ ምዕባይ ግንዛበ መንሽሮ ጡብ፡ 'ኣብ ዝኾነ ዕድመ ዘጋጥም ምዃኑ ኣነ ምስክር'የ'  ሉሲ መጀመርታ ኣብ ጡባ ሕበጥ ክትረክብ እንከላ፡ ፈጺሙ መንሽሮ [ካንሰር] ክኸውን'ዩ ዝብል ግምት ኣይነበራን። ጡባ ናይ ምፍታሽ ልምዲ ስለ ዘይነበራ "ሃንደበት" እያ ኣብቲ ከባቢ ሕበጥ...           tir      Tigrinya
9                              ንብዙሓት ዘቖጠዐ ጉዳይ ብጥሜት ዝተታሕዙ ኣናብስ ሱዳን  ኩነታት ናይቶም ኣብ ሓደ ኣብ ርእሰከተማ ካርቱም ዝርከብ መካነ-እንስሳታት ተዳጒኖም ዘለዉን ብሰንኪ ጥሜት ኣብ ኣፍሞት ዝበጽሑን ኣናብስ፡ ኣብ ህዝቢ ሓያል ቁጠዐ ፈጢሩ። ዘስንብድ ስእሊ...           tir      Tigrinya

======================================================================
  Language: isiXhosa (xho)
======================================================================

                                                                headline                                                                                                                     text language_code language_name
0                                                 Iinguqu kwiRadio 2000!  Isikhululo seSABC, iRadio 2000, yenze utshintsho kubume beenkqubo zesi khululo. \nOku kuza emva kokulahla kukaCarol ...           xho      isiXhosa
1        Intatheli yeSolezwe ifumene iwonga lokubalasela kwezobuntatheli  INTATHELI yephephandaba I’solezwe LesiXhosa, uSithandiwe Velaphi, ithi imbasa eyifumene kwimpelaveki ephelileyo luph...           xho      isiXhosa
2  Abalandeli bakaTwitter banezimvo ezitenxileyo ngomntu omtsha kaBoity!  INGATHI kanti umntu ozakuthathela umntu wakho ngulo usecaleni kwakho, ezo zizimvo zoluntu kuTwitter emva kweendaba e...           xho      isiXhosa
3         ABafana Bafana bayibambe aphi incinci khona iSenegal namhlanje  Iqhayiya lesizwe – iBafana Bafana – lidlale oyena mdlali oncumisayo emva kwethuba elide lagqibela ngethuba libetha i...           xho      isiXhosa
4                                   Mabuyane: ‘Siyabulela kuni bephondo’  INKULUBAPHATHISWA yaseMpuma Koloni, uOscar Mabuyane, wenze umbulelo kubantu bephondo ngokuphuma bayovota, nangona nj...           xho      isiXhosa
5                    UParker uthi abaqinisekanga ngekamva labo kwiChiefs  Ifolosi yeKaizer Chiefs, uBernard Parker, ithi akukho namnye umdlali oqinisekileyo ngendawo yakhe njengokuba kulungi...           xho      isiXhosa
6                                                              #TheQueen  Singalindela ntoni kumdlalo omtsha – iThe Queen, nekudlala kuwo uConnie Ferguson,Sello Maake kaNcube, Shona Ferguson...           xho      isiXhosa
7                            Njedu: Kunyanzelekile siphumelele namhlanje  Umqeqeshi we-EC Bees, uVuyisile “Chippa” Njedu, uvumile ukuba ngokwenene iqela lakhe liphantsi koxinizelelo emva kok...           xho      isiXhosa
8                                 Ugawulayo akabulali, kubulala ubuyatha  Uzungabuhoyi ubuyatha bam, Uzungabuhoyi ubuciko bam, Uzungabunaki ubuhle bam, Uzungabuhoyi ubudenge bam, Uze ungandi...           xho      isiXhosa
9                         Umbuso ulindele iimpepha zokubhubha kukaTantsi  IBUTHO lophando ooKhetshe (Hawks) lizakuva kwiGunya-Bantu lezoTshutshiso malunga nomkhombandlela kwityala lobuqhetse...           xho      isiXhosa

======================================================================
  Language: Yoruba (yor)
======================================================================

                                                                                                            headline                                                                                                                     text language_code language_name
0                                     Tí ìgbẹ́ tóò ń yà bá rí báyìí? Àìsàn jẹjẹrẹ ikùn ló dé o! Wo bí wàá ṣe dàa mọ̀  Ìlera ní Yorùbá pè ní oògùn ọrọ̀, àláfíà ẹni kọ̀ọ̀kan wa kò sì ní di fíafìa. Onírúurú àìsàn ló wà lóde òní tó jẹ́ wí...           yor        Yoruba
1                                            Breastfeeding: Wo àwọn oúnjẹ́ tí yóò mú kí omi ọmú pọ̀ si fún ìyálọ́mọ́  Ọpọlọpọ ounjẹ lo wa, to le ṣe awọn iyalọmọ to n fun ọmọ ni ọyan ni anfaani, ki omi ọmu wọn le pọ si. Iru ounjẹ ti ob...           yor        Yoruba
2                             Pastor Adeboye: Ìyàwó Adeboye ní ó jẹ́ okùnrin tí gbogbo obìnrin fẹ́ràn láti fi ṣe ọkọ  Iyawo pasitọ Enoch Adeboye, Foluke Adeboye ti sapajuwe ọkọ rẹ gẹgẹ bi ọkunrin akinkanju ti gbogbo obinrin fẹran lati...           yor        Yoruba
3                                                             Charles Olumo Agbako ń ṣe àìsàn ńlá, ó ní ara ń ni òun  Òdú ni gbajúgbajà òṣèré tíátà nnì, Abdulsalam Ishola ẹni tí ọ̀pọ̀lọpọ̀ mọ̀ sí Charles Olúmọ Àgbákò lagbo tiata. Láàá...           yor        Yoruba
4  US Fake Marriage Pastor: Ẹ̀wọ̀n ọdún márùn-ún ni ìkọ̀ọ̀kan ẹ̀sùn jìbìtì àti irọ́ pípa tí wọn fi kan Pásítọ̀ gbérù  Olusọagutan kan ni Maryland lorilẹede Amẹrika, tii se ẹni aadọta ọdun, Joshua Olatokunbo Shonubi ni wọn ti fi ẹsun k...           yor        Yoruba
5                                              Yinka Ayefele: Ìrọ́ ni pé ń kò le ṣe bíi ọkùnrin, mò ń ta pútú dàadáa  Awọn agba ni ẹni ti yoo ga, ẹsẹ rẹ yoo tiirin, bẹẹ si ni bi ẹni ti yoo ba ni ogo, yoo ri ohun sọ nitori inu ẹgbin ni...           yor        Yoruba
6                                   Ìdí tí àwọn ìbejì mi, Twinz love ṣe ń rí mi mú fi ṣe “prank” wọn rèé – Ìyá Ìbejì  “A ṣe prank gbe ọkan lara wa loyun fun iya ibeji, wọn sọkun gidi gan, koda bi a ṣe pada sọ pe irọ ni, wọn ṣi balẹ si...           yor        Yoruba
7                                Pasuma: Ọ̀gáńlá Fújì ní ominú ń kọ òun lórí ọ̀dá àwọn ìràwọ̀ tuntun lágbo orin Fújì  Gbajugbaja akọrin Fuji ni, Alhaji Wasiu Alabi ti ọpọ eeyan mọ si Pasuma Wonder, iba wasi baba baraka ti ṣalaye pe ọr...           yor        Yoruba
8  Ekiti state PDP Congress: Fayose, Olujimi, Oni ń forígbárí nítorí ìdìbò wọ́ọ̀dù tó wáyé lẹ́gbẹ́ òṣèlú PDP l'Ekiti  Ina edeaiyede n jo laarin awọn eekan oloṣelu lẹgbẹ oṣelu PDP ni ipinlẹ Ekiti paapaa laarin igun gomina tẹlẹ, Ayọ Fay...           yor        Yoruba
9                                                                   Mama Arsenal: Ẹgbẹ́ kan ti fún màmá ní ẹ̀bùn owó  Bi a ba ku, iṣe o tan ni Yoruba maa n wi. Bẹẹ gẹlẹ ni ọrọ ri pẹlu mama agba ololufẹ ẹgbẹ agbabọọlu Arsenal, Nosimatu...           yor        Yoruba

---
## 4. Building the Human Text Dataset

This section draws from the three datasets loaded above to assemble the final
human-written text corpus used for classifier training.

**Language and source selection:**

| Language | Source | Column Used | Reason |
|----------|--------|-------------|--------|
| Yoruba | AfriSenti | `tweet` | Rich informal social media text in Yoruba |
| isiZulu | Vukuzenzele | `text` | Formal government text — only SA source with Zulu |
| chiShona | MasakhaNEWS | `text` | Structured news articles covering diverse topics |

**Sampling strategy:**
- **2,000 rows per language** are selected to keep the dataset balanced — no language
  dominates model training.
- `random_state=42` ensures the same rows are selected every time the notebook is run,
  making results reproducible across team members.
- `.dropna()` and `.drop_duplicates()` are applied before sampling to ensure all
  2,000 selected rows contain clean, unique text.

**Labelling:**
All rows are assigned `label = 0` and `label_name = "human"` to mark them as
human-written text. Machine-generated text (GPT) will later be assigned `label = 1`
and combined with this dataset to form the full training corpus.

**Final shape:** 6,000 rows × 4 columns (`text`, `language_code`, `language_name`, `label`)

In [ ]:
# ── 1. Yoruba — from AfriSenti (tweet column) ─────────────────────────────
yoruba_df = (
    afrisenti_dfs['yor'][['tweet']]
    .rename(columns={'tweet': 'text'})
    .dropna()
    .drop_duplicates()
    .sample(n=2000, random_state=42)
    .reset_index(drop=True)
)
yoruba_df['language_code'] = 'yor'
yoruba_df['language_name'] = 'Yoruba'
print(f"  Yoruba  (AfriSenti)   — {len(yoruba_df):,} rows")

# ── 2. isiZulu — from Vukuzenzele (text column) ───────────────────────────
zulu_df = (
    vukuzenzele_dfs['zul'][['text']]
    .dropna()
    .drop_duplicates()
    .sample(n=2000, random_state=42)
    .reset_index(drop=True)
)
zulu_df['language_code'] = 'zul'
zulu_df['language_name'] = 'isiZulu'
print(f"  isiZulu (Vukuzenzele) — {len(zulu_df):,} rows")

# ── 3. swahili — from MasakhaNEWS (text column) ─────────────────────────
swahili_df = (
    masakhane_dfs['swa'][['text']]
    .dropna()
    .drop_duplicates()
    .sample(n=2000, random_state=42)
    .reset_index(drop=True)
)
swahili_df['language_code'] = 'swa'
swahili_df['language_name'] = 'swahili'
print(f"  chiShona (MasakhaNEWS) — {len(swahili_df):,} rows")

# ── 4. Combine and label ──────────────────────────────────────────────────
human_df = (
    pd.concat([yoruba_df, zulu_df, swahili_df], ignore_index=True)
    .sample(frac=1, random_state=42)   # shuffle
    .reset_index(drop=True)
)
human_df['label']      = 0
human_df['label_name'] = 'human-text'

# ── 5. Summary ────────────────────────────────────────────────────────────
print(f"\n{'='*50}")
print(f"  HUMAN TEXT DATASET SUMMARY")
print(f"{'='*50}")
print(f"  Total rows  : {len(human_df):,}")
print(f"  Columns     : {list(human_df.columns)}")
print(f"\n  Per language:")
print(human_df['language_name'].value_counts().to_string())
print(f"\n  Label distribution:")
print(human_df['label_name'].value_counts().to_string())
print()
display(human_df.head(10))

  Yoruba  (AfriSenti)   — 2,000 rows
  isiZulu (Vukuzenzele) — 2,000 rows
  chiShona (MasakhaNEWS) — 2,000 rows

==================================================
  HUMAN TEXT DATASET SUMMARY
==================================================
  Total rows  : 6,000
  Columns     : ['text', 'language_code', 'language_name', 'label', 'label_name']

  Per language:
language_name
Yoruba     2000
isiZulu    2000
swahili    2000

  Label distribution:
label_name
human-text    6000

                                                                                                                      text language_code language_name  label  label_name
0               Ẹní tó mọ wúrà la ńtàá fún. / Gold ought to be sold to the one who values it. #Swissgolden #yoruba proverb           yor        Yoruba      0  human-text
1  Lobu bugebengu buthunaza kakhulu umnotho njengoba izinkampani zingakwazi ukuthutha imikhiqizo yazo iye emachwe beni ...           zul       isiZulu      0  human-text
2  RT @user: Ode roko, ode pa eran, eran kini ode pa, Ode pa eran okete..... Iku a re wa kete, Aisan a re wa ke te, A r...           yor        Yoruba      0  human-text
3                Sekuqinisekisiwe ukuthi lokhu akuhlangene neminyaka yobudala, isimo senhlalo nomnotho, ibala noma inkolo.           zul       isiZulu      0  human-text
4  Raila Odinga amepinga matokeo ya uchaguzi wa urais akisema kuwa idadi iliyotangazwa  Jumatatu ilikuwa ni  "batili na...           swa       swahili      0  human-text
5                                                                                       yoruba word of the day relax sinmi           yor        Yoruba      0  human-text
6  Gẹ́gẹ́ bí Dọ́kítà Brimmy Ọlágbhẹ̀rẹ̀ ṣe sọ, ó nípé irọ́ ńlá ni wípé a kò mọ̀n ọ́n kọ kí èèbó tó gòkè. #EdeAbinibi #Y...           yor        Yoruba      0  human-text
7                 ọ̀rúnmìlà pàápàá wọ ọ̀run lọ inú igi ọ̀pẹ búkà mẹ́rìndínlógún ló sì gbà lọ mà á sọ ìtàn nì lọ́jọ́ àjínde           yor        Yoruba      0  human-text
8  RT @user: Òjíjí bá jí wọn, ẹnikẹ́ni tí ìrànlọ́wọ́ọ̀ mi bá ń bẹ níkàwọ́ọ rẹ̀. Afà máa fà wọ́n bọ̀ pitipiti. Nítorí ẹṣ...           yor        Yoruba      0  human-text
9  Ọpẹ́lọpẹ́ àwọn obí tí wọ́n ro ti ọjọ́'wájú, bóyá irú àwà yìí ò bá má gbọ́ Yoòbá. A bá máa fi'mú sọ̀rọ̀ sírawa nínú i...           yor        Yoruba      0  human-text

---
## 5. Machine-Generated Text Dataset

This section loads GPT-generated text for the same three languages used in the
human text dataset. The machine text was produced by prompting GPT with
language- and topic-specific instructions designed to match the style, length,
and domain of the human text as closely as possible.

**Language and source selection:**

| Language | Matched Human Source | GPT Style Instruction |
|----------|---------------------|----------------------|
| Yoruba | AfriSenti tweets | Informal social media posts |
| isiZulu | Vukuzenzele government articles | Formal government magazine style |
| Swahili | MasakhaNEWS articles | BBC/VOA journalistic style |

**Labelling:**
All rows are assigned `label = 1` and `label_name = "machine-text"` to mark them
as machine-generated. This dataset will be combined with the human text dataset
(label = 0) to form the full 12,000-row training corpus.

**File format expected:**
Each CSV must have a single column named `text`, one sentence/paragraph per row.
Place files in the same directory as this notebook before running.

In [ ]:
def split_to_sentences(text, min_words=4):
    if not isinstance(text, str):
        return []
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    result = []
    for s in sentences:
        for sub in s.split('\n'):
            sub = sub.strip().strip('"').strip("'")
            if len(sub.split()) >= min_words:
                result.append(sub)
    return result


def load_machine_file(filepath, lang_code):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        raw = f.read()
    sentences = []
    blocks = re.split(r'\r?\n\r?\n', raw)
    if len(blocks) > 10:
        for block in blocks:
            block = block.strip()
            if block:
                sentences.extend(split_to_sentences(block))
    else:
        lines = [l.strip().strip('"').strip("'")
                 for l in raw.split('\n') if l.strip()]
        if lines and lines[0].lower() in ['text', 'sentence', 'content']:
            lines = lines[1:]
        for line in lines:
            sentences.extend(split_to_sentences(line))
    return list(dict.fromkeys(sentences))


MACHINE_FILES = {
    'yor': ('/content/drive/MyDrive/COS760/machine_yoruba.csv',         'Yoruba'),
    'zul': ('/content/drive/MyDrive/COS760/machine_zulu.csv',    'isiZulu'),
    'swa': ('/content/drive/MyDrive/COS760/machine_swahili.csv', 'Swahili'),
}

machine_dfs = {}
print("Loading and splitting machine-generated text...\n")

for lang_code, (filepath, lang_name) in MACHINE_FILES.items():
    if not os.path.exists(filepath):
        print(f"  [MISSING] {lang_code}  —  {filepath} not found")
        continue
    sentences = load_machine_file(filepath, lang_code)
    lang_df = pd.DataFrame({'text': sentences})
    lang_df['language_code'] = lang_code
    lang_df['language_name'] = lang_name
    machine_dfs[lang_code] = lang_df
    print(f"  [OK]   {lang_code}  —  {len(lang_df):,} sentences")

# ── Check available counts before sampling ────────────────────────────────
print(f"\n  Available sentences per language:")
for lc, df in machine_dfs.items():
    status = 'OK' if len(df) >= 500 else 'LOW — consider generating more'
    print(f"    {lc}: {len(df):,}  [{status}]")

# ── Sample to balanced size ───────────────────────────────────────────────
MACHINE_SAMPLE = min(600, *[len(df) for df in machine_dfs.values()])
print(f"\n  Sampling {MACHINE_SAMPLE} sentences per language")

machine_yoruba_df  = machine_dfs['yor'].sample(n=MACHINE_SAMPLE, random_state=42).reset_index(drop=True)
machine_zulu_df    = machine_dfs['zul'].sample(n=MACHINE_SAMPLE, random_state=42).reset_index(drop=True)
machine_swahili_df = machine_dfs['swa'].sample(n=MACHINE_SAMPLE, random_state=42).reset_index(drop=True)

# ── Combine and label = 1 ─────────────────────────────────────────────────
machine_df = (
    pd.concat([machine_yoruba_df, machine_zulu_df, machine_swahili_df],
              ignore_index=True)
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)
machine_df['label']      = 1
machine_df['label_name'] = 'machine-text'

print(f"\n{'='*50}")
print(f"  MACHINE TEXT DATASET SUMMARY")
print(f"{'='*50}")
print(f"  Total rows : {len(machine_df):,}")
print(f"  Per language:")
print(machine_df['language_name'].value_counts().to_string())
print()
display(machine_df.head(10))

Loading and splitting machine-generated text...

  [OK]   yor  —  1,038 sentences
  [OK]   zul  —  654 sentences
  [OK]   swa  —  651 sentences

  Available sentences per language:
    yor: 1,038  [OK]
    zul: 654  [OK]
    swa: 651  [OK]

  Sampling 600 sentences per language

==================================================
  MACHINE TEXT DATASET SUMMARY
==================================================
  Total rows : 1,800
  Per language:
language_name
Swahili    600
isiZulu    600
Yoruba     600

                                                                                      text language_code language_name  label    label_name
0                    Wataalamu wa matibabu wametoa ushauri wa kunywa maji mengi kila siku.           swa       Swahili      1  machine-text
1  Amaphrojekthi amanzi aseNorth West aletha amanzi ahlanzekile emiphakathini yasemakhaya.           zul       isiZulu      1  machine-text
2                                 Abafundi baseKwaZulu-Natal bathola uxhaso lwezokuthutha.           zul       isiZulu      1  machine-text
3                                                                     Bọọlu ti win fun mi.           yor        Yoruba      1  machine-text
4                                                        Wakati huu, nafasi yake ni nzuri.           swa       Swahili      1  machine-text
5                                                         Goal náà sweet bí chilled water.           yor        Yoruba      1  machine-text
6                                                          Football dey humble proud fans.           yor        Yoruba      1  machine-text
7                                                           Church testimony give me hope.           yor        Yoruba      1  machine-text
8                                             Yanga SC imepata mchezaji mpya wa kimataifa.           swa       Swahili      1  machine-text
9               Abafundi baseThekwini bathola iNSFAS futhi baqede iziqu zabo ngempumelelo.           zul       isiZulu      1  machine-text

---
## 6. Combining Human and Machine Text into the Final Training Dataset

Now that both datasets are ready, they are merged into a single DataFrame
that the classifier will train on.

**Structure of the final dataset:**

| Column | Description |
|--------|-------------|
| `text` | The sentence or paragraph |
| `language_code` | Language identifier (`yor`, `zul`, `swa`) |
| `language_name` | Full language name |
| `label` | `0` = human-written, `1` = machine-generated |
| `label_name` | `human-text` or `machine-text` |

**Why combine?**
The model learns to distinguish human from machine text by seeing both
classes together during training. Keeping them separate would mean the
model has nothing to compare against.

**Balance check:**
Both datasets must have equal or near-equal row counts per language so
the model does not develop a bias toward whichever class has more samples.

In [ ]:
# ── Combine human (label=0) and machine (label=1) ─────────────────────────
full_df = (
    pd.concat([human_df, machine_df], ignore_index=True)
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

# ── Summary ───────────────────────────────────────────────────────────────
print(f"{'='*55}")
print(f"  FULL COMBINED DATASET SUMMARY")
print(f"{'='*55}")
print(f"  Total rows     : {len(full_df):,}")
print(f"  Columns        : {list(full_df.columns)}")

print(f"\n  Label balance:")
label_counts = full_df['label_name'].value_counts()
print(label_counts.to_string())
ratio = label_counts.min() / label_counts.max()
print(f"  Balance ratio  : {ratio:.2f}  (1.0 = perfectly balanced)")

print(f"\n  Per language:")
print(full_df.groupby(['language_name', 'label_name']).size()
      .unstack(fill_value=0).to_string())

print()
display(full_df.head(10))

# ── Save to Google Drive ──────────────────────────────────────────────────
save_path = '/content/drive/MyDrive/COS760/full_dataset.csv'
full_df.to_csv(save_path, index=False)
print(f"\n  Saved to: {save_path}")
print(f"  This file is your input for the classification notebook.")

=======================================================
  FULL COMBINED DATASET SUMMARY
=======================================================
  Total rows     : 7,800
  Columns        : ['text', 'language_code', 'language_name', 'label', 'label_name']

  Label balance:
label_name
human-text      6000
machine-text    1800
  Balance ratio  : 0.30  (1.0 = perfectly balanced)

  Per language:
label_name     human-text  machine-text
language_name
Swahili                 0           600
Yoruba               2000           600
isiZulu              2000           600
swahili              2000             0

                                                                                                                      text language_code language_name  label    label_name
0                                  Abasizi bothisha abaqashwe eMgungundlovu basebenzi sa imali yabo yomholo eMgungundlovu.           zul       isiZulu      0    human-text
1  Simulizi ya mafanikio ya demokrasia ,katika taifa la magharibi ambalo liliingia kwenye mfumo wa vyama vingi kuanzia ...           swa       swahili      0    human-text
2  Fún ìwádìí náà, a ṣe àyálò ètò oúnjẹ sísè láti ìlú America fún ọmọìlú Brazil, tí a pè ní Ìṣaralóore àti oúnjẹ sísè n...           yor        Yoruba      0    human-text
3  Bẹ́ẹ̀, ó sì lè ṣe ọmọ ogun lábẹ́ olórí ogun rẹ̀. Gẹ́gẹ́ bíi ọmọ ogun tí a bí ní ìbí ọmọ, ẹrú tó gba òmìnira yìí ní l...           yor        Yoruba      0    human-text
4  Nípa ti ọ̀rọ oúnjẹ nílùú mi. A ní ẹranko àti òwú, ṣùgbọ́n ọmọ ẹlẹ́ran wa ti ń jẹ egun, aláṣọ wa ti ń wọ àkísà. #OmiI...           yor        Yoruba      0    human-text
5  Bebesebenzisana nabo bonke ababambiqhaza kuzo zonke lezi zindawo ukuqinisekisa ukuthi sibambisana ngempumelelo ezinh...           zul       isiZulu      0    human-text
6                                   •\tGcina inombolo yosizo oluphuthumayo njenge-ambulensi nenombolo yamaphoyisa iseduze.           zul       isiZulu      0    human-text
7                                                                  Izikhungo zezempilo ziqhubeka nokuhlola umfutho wegazi.           zul       isiZulu      1  machine-text
8                                                                                             Mradi wa mbegu umezinduliwa.           swa       Swahili      1  machine-text
9                                                Wataalamu wa meno wametoa vidokezo vya kusafisha meno mara tatu kwa siku.           swa       Swahili      1  machine-text

  Saved to: /content/drive/MyDrive/COS760/full_dataset.csv
  This file is your input for the classification notebook.

---
## 7. Train / Test Split (70% / 30%)

With the combined dataset ready, the next step is to split it into a
**training set** and a **test set** following the same approach used in HW2.2.

**Why split?**
The model is trained on the training set and evaluated on the test set —
data the model has never seen before. This gives an honest measure of how
well the model generalises beyond the examples it learned from.

**Stratified split:**
A stratified split is used so that both the training and test sets contain
the same proportion of human and machine text. Without stratification,
random chance could put most of the machine text in training and leave
very little in the test set, making evaluation unreliable.

| Set | Size | Human rows | Machine rows |
|-----|------|-----------|--------------|
| Training | 70% | balanced | balanced |
| Test | 30% | balanced | balanced |

**Variables produced:**
- `text_train` / `text_test` — raw text for vectorization
- `y_train` / `y_test` — labels (0 = human, 1 = machine)
- `lang_train` / `lang_test` — language codes (used for per-language evaluation later)

In [ ]:
# ── Input ─────────────────────────────────────────────────────────────────
X    = full_df['text']       # raw text
y    = full_df['label']      # 0 = human, 1 = machine
lang = full_df['language_code']

# ── Stratified 70/30 split ────────────────────────────────────────────────
# stratify=y ensures equal human/machine ratio in both sets
# random_state=42 makes the split reproducible for all team members
text_train, text_test, y_train, y_test, lang_train, lang_test = train_test_split(
    X, y, lang,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# ── Verify split sizes (from HW2.2 assertion) ─────────────────────────────
assert (0.3 - len(y_test) / len(y)) < 0.001, "Test size is not approximately 30%"

# ── Summary ───────────────────────────────────────────────────────────────
print(f"{'='*55}")
print(f"  TRAIN / TEST SPLIT SUMMARY")
print(f"{'='*55}")
print(f"  Total dataset  : {len(y):,} rows")
print(f"  Training set   : {len(y_train):,} rows  ({len(y_train)/len(y)*100:.0f}%)")
print(f"  Test set       : {len(y_test):,} rows  ({len(y_test)/len(y)*100:.0f}%)")

print(f"\n  Training set class balance:")
print(f"    Human   (0) : {(y_train==0).sum():,}")
print(f"    Machine (1) : {(y_train==1).sum():,}")

print(f"\n  Test set class balance:")
print(f"    Human   (0) : {(y_test==0).sum():,}")
print(f"    Machine (1) : {(y_test==1).sum():,}")

print(f"\n  Baseline accuracy to beat : {1 - np.mean(y_train):.4f}")
print(f"  (majority class classifier — always predicts 'human')")

=======================================================
  TRAIN / TEST SPLIT SUMMARY
=======================================================
  Total dataset  : 7,800 rows
  Training set   : 5,460 rows  (70%)
  Test set       : 2,340 rows  (30%)

  Training set class balance:
    Human   (0) : 4,200
    Machine (1) : 1,260

  Test set class balance:
    Human   (0) : 1,800
    Machine (1) : 540

  Baseline accuracy to beat : 0.7692
  (majority class classifier — always predicts 'human')

---
## 8. Feature Extraction

Before training, the raw text must be converted into numerical vectors
that the Logistic Regression classifier can process. Following the same
approach as HW2.2, two representations are built and compared:

| Method | What it does |
|--------|-------------|
| **CountVectorizer (TF)** | Counts how many times each word appears in a document — raw word frequency |
| **TF-IDF** | Weights word frequency by how rare the word is across all documents — common words like "the" get downweighted |

Both vectorizers are **fitted only on the training set** and then applied
to the test set. This prevents the model from seeing test data during
training — the same principle as the train/test split itself.

In [ ]:

# ── Vectorizer functions from HW2.2 ───────────────────────────────────────
def initialise_term_frequency_vectorizer(data):
    vectorizer_tf = CountVectorizer()
    vectorizer_tf.fit(data)
    X = vectorizer_tf.transform(data)
    return X, vectorizer_tf

def initialise_tfidf_vectorizer(data):
    vectorizer_tfidf = TfidfVectorizer()
    vectorizer_tfidf.fit(data)
    X = vectorizer_tfidf.transform(data)
    return X, vectorizer_tfidf

# ── Fit on training set only ──────────────────────────────────────────────
X_train,       vectorizer_tf    = initialise_term_frequency_vectorizer(text_train)
X_train_tfidf, vectorizer_tfidf = initialise_tfidf_vectorizer(text_train)

# ── Transform test set using the same fitted vectorizers ──────────────────
X_test       = vectorizer_tf.transform(text_test)
X_test_tfidf = vectorizer_tfidf.transform(text_test)

print(f"  CountVectorizer vocab size : {len(vectorizer_tf.vocabulary_):,}")
print(f"  TF-IDF vocab size          : {len(vectorizer_tfidf.vocabulary_):,}")
print(f"  X_train shape              : {X_train.shape}")
print(f"  X_train_tfidf shape        : {X_train_tfidf.shape}")
print(f"  X_test shape               : {X_test.shape}")
print(f"  X_test_tfidf shape         : {X_test_tfidf.shape}")

  CountVectorizer vocab size : 74,498
  TF-IDF vocab size          : 74,498
  X_train shape              : (5460, 74498)
  X_train_tfidf shape        : (5460, 74498)
  X_test shape               : (2340, 74498)
  X_test_tfidf shape         : (2340, 74498)

---
## 9. Logistic Regression Classifier

A Logistic Regression classifier is trained on both feature sets,
following the same structure as HW2.2.

**Why Logistic Regression?**
It is a strong, interpretable baseline for text classification. Its
coefficients directly show which words most strongly signal human vs
machine text — making it useful for the linguistic analysis part of
this project.

**Evaluation metrics used:**

| Metric | Why it matters here |
|--------|-------------------|
| **Accuracy** | Overall correct predictions |
| **F1-score** | Better for understanding precision/recall trade-off — important if classes are slightly imbalanced |
| **5-fold cross-validation** | Gives a stable estimate of performance across different subsets of training data |

As noted in HW2.2 Q2.4: F1-score is preferred over accuracy alone
because a model could achieve high accuracy simply by always predicting
the majority class, completely failing to detect the minority class.

In [ ]:

# ═══════════════════════════════════════════════════════════
#  9.1  CountVectorizer (TF) — Logistic Regression
# ═══════════════════════════════════════════════════════════
clf = LogisticRegression(max_iter=1000)

scores    = cross_val_score(clf, X_train, y_train, cv=5)
scores_f1 = cross_val_score(clf, X_train, y_train, cv=5, scoring='f1')

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("CountVectorizer (TF) — Logistic Regression")
print(f"  5-Fold CV Accuracy : {scores.mean():.4f}  (+/- {scores.std()*2:.4f})")
print(f"  5-Fold CV F1       : {scores_f1.mean():.4f}  (+/- {scores_f1.std()*2:.4f})")
print(f"\n  Test Accuracy : {accuracy_score(y_test, y_pred):.4f}")
print(f"  Test F1       : {f1_score(y_test, y_pred):.4f}")
print()
print(classification_report(y_test, y_pred,
      target_names=['human (0)', 'machine (1)'], digits=4))

# ═══════════════════════════════════════════════════════════
#  9.2  TF-IDF — Logistic Regression
# ═══════════════════════════════════════════════════════════
clf_tfidf = LogisticRegression(max_iter=1000)

scores_tfidf    = cross_val_score(clf_tfidf, X_train_tfidf, y_train, cv=5)
scores_tfidf_f1 = cross_val_score(clf_tfidf, X_train_tfidf, y_train, cv=5, scoring='f1')

clf_tfidf.fit(X_train_tfidf, y_train)
y_pred_tfidf = clf_tfidf.predict(X_test_tfidf)

print("TF-IDF — Logistic Regression")
print(f"  5-Fold CV Accuracy : {scores_tfidf.mean():.4f}  (+/- {scores_tfidf.std()*2:.4f})")
print(f"  5-Fold CV F1       : {scores_tfidf_f1.mean():.4f}  (+/- {scores_tfidf_f1.std()*2:.4f})")
print(f"\n  Test Accuracy : {accuracy_score(y_test, y_pred_tfidf):.4f}")
print(f"  Test F1       : {f1_score(y_test, y_pred_tfidf):.4f}")
print()
print(classification_report(y_test, y_pred_tfidf,
      target_names=['human (0)', 'machine (1)'], digits=4))

# ═══════════════════════════════════════════════════════════
#  9.3  Improved Vectorizers — unigrams + bigrams (from HW2.2 Q3)
# ═══════════════════════════════════════════════════════════
vectorizer_tf_improved    = CountVectorizer(ngram_range=(1, 2), max_features=5000)
vectorizer_tfidf_improved = TfidfVectorizer(ngram_range=(1, 2), max_features=5000,
                                            sublinear_tf=True)

X_train_improved       = vectorizer_tf_improved.fit_transform(text_train)
X_train_tfidf_improved = vectorizer_tfidf_improved.fit_transform(text_train)
X_test_improved        = vectorizer_tf_improved.transform(text_test)
X_test_tfidf_improved  = vectorizer_tfidf_improved.transform(text_test)

clf_imp = LogisticRegression(max_iter=1000)

scores_acc_tf    = cross_val_score(clf_imp, X_train_improved,       y_train, cv=5)
scores_f1_tf     = cross_val_score(clf_imp, X_train_improved,       y_train, cv=5, scoring='f1')
scores_acc_tfidf = cross_val_score(clf_imp, X_train_tfidf_improved, y_train, cv=5)
scores_f1_tfidf  = cross_val_score(clf_imp, X_train_tfidf_improved, y_train, cv=5, scoring='f1')

print("Improved CountVectorizer (unigrams + bigrams, max 5000 features)")
print(f"  CV Accuracy : {scores_acc_tf.mean():.4f}  (+/- {scores_acc_tf.std()*2:.4f})")
print(f"  CV F1       : {scores_f1_tf.mean():.4f}  (+/- {scores_f1_tf.std()*2:.4f})")

print("\nImproved TF-IDF (unigrams + bigrams, sublinear_tf, max 5000 features)")
print(f"  CV Accuracy : {scores_acc_tfidf.mean():.4f}  (+/- {scores_acc_tfidf.std()*2:.4f})")
print(f"  CV F1       : {scores_f1_tfidf.mean():.4f}  (+/- {scores_f1_tfidf.std()*2:.4f})")

# ═══════════════════════════════════════════════════════════
#  9.4  Full Results Comparison Table
# ═══════════════════════════════════════════════════════════
results = pd.DataFrame([
    {
        'Model':         'CountVec (TF)',
        'CV Accuracy':   f"{scores.mean():.4f}",
        'CV F1':         f"{scores_f1.mean():.4f}",
        'Test Accuracy': f"{accuracy_score(y_test, y_pred):.4f}",
        'Test F1':       f"{f1_score(y_test, y_pred):.4f}"
    },
    {
        'Model':         'TF-IDF',
        'CV Accuracy':   f"{scores_tfidf.mean():.4f}",
        'CV F1':         f"{scores_tfidf_f1.mean():.4f}",
        'Test Accuracy': f"{accuracy_score(y_test, y_pred_tfidf):.4f}",
        'Test F1':       f"{f1_score(y_test, y_pred_tfidf):.4f}"
    },
    {
        'Model':         'CountVec improved (1-2 gram)',
        'CV Accuracy':   f"{scores_acc_tf.mean():.4f}",
        'CV F1':         f"{scores_f1_tf.mean():.4f}",
        'Test Accuracy': '-',
        'Test F1':       '-'
    },
    {
        'Model':         'TF-IDF improved (1-2 gram)',
        'CV Accuracy':   f"{scores_acc_tfidf.mean():.4f}",
        'CV F1':         f"{scores_f1_tfidf.mean():.4f}",
        'Test Accuracy': '-',
        'Test F1':       '-'
    },
])

print("="*60)
print("  FULL RESULTS COMPARISON")
print("="*60)
display(results)

CountVectorizer (TF) — Logistic Regression
  5-Fold CV Accuracy : 0.9674  (+/- 0.0077)
  5-Fold CV F1       : 0.9309  (+/- 0.0181)

  Test Accuracy : 0.9778
  Test F1       : 0.9531

              precision    recall  f1-score   support

   human (0)     0.9932    0.9778    0.9854      1800
 machine (1)     0.9296    0.9778    0.9531       540

    accuracy                         0.9778      2340
   macro avg     0.9614    0.9778    0.9693      2340
weighted avg     0.9785    0.9778    0.9780      2340

TF-IDF — Logistic Regression
  5-Fold CV Accuracy : 0.9330  (+/- 0.0151)
  5-Fold CV F1       : 0.8298  (+/- 0.0441)

  Test Accuracy : 0.9496
  Test F1       : 0.8778

              precision    recall  f1-score   support

   human (0)     0.9394    0.9989    0.9682      1800
 machine (1)     0.9953    0.7852    0.8778       540

    accuracy                         0.9496      2340
   macro avg     0.9673    0.8920    0.9230      2340
weighted avg     0.9523    0.9496    0.9474      2340

Improved CountVectorizer (unigrams + bigrams, max 5000 features)
  CV Accuracy : 0.9353  (+/- 0.0117)
  CV F1       : 0.8655  (+/- 0.0257)

Improved TF-IDF (unigrams + bigrams, sublinear_tf, max 5000 features)
  CV Accuracy : 0.9297  (+/- 0.0123)
  CV F1       : 0.8283  (+/- 0.0342)
============================================================
  FULL RESULTS COMPARISON
============================================================

                          Model CV Accuracy   CV F1 Test Accuracy Test F1
0                 CountVec (TF)      0.9674  0.9309        0.9778  0.9531
1                        TF-IDF      0.9330  0.8298        0.9496  0.8778
2  CountVec improved (1-2 gram)      0.9353  0.8655             -       -
3    TF-IDF improved (1-2 gram)      0.9297  0.8283             -       -

In [ ]:
# Save trained models to Google Drive
model_dir = '/content/drive/MyDrive/COS760/models'
os.makedirs(model_dir, exist_ok=True)

with open(f'{model_dir}/vectorizer_tf.pkl',   'wb') as f: pickle.dump(vectorizer_tf,    f)
with open(f'{model_dir}/classifier_tf.pkl',   'wb') as f: pickle.dump(clf,              f)
with open(f'{model_dir}/vectorizer_tfidf.pkl','wb') as f: pickle.dump(vectorizer_tfidf, f)
with open(f'{model_dir}/classifier_tfidf.pkl','wb') as f: pickle.dump(clf_tfidf,        f)

print("Models saved:")
for fname in os.listdir(model_dir):
    size = os.path.getsize(f'{model_dir}/{fname}')
    print(f"  {fname}  ({size/1024:.0f} KB)")

Models saved:
  vectorizer_tf.pkl  (1080 KB)
  classifier_tf.pkl  (583 KB)
  vectorizer_tfidf.pkl  (1663 KB)
  classifier_tfidf.pkl  (583 KB)

---
## 10. Fine-Tuned Transformer Models

Logistic Regression with bag-of-words features treats every word independently and has no understanding of word order or context. Transformer models learn deep **contextual representations** — the same word gets a different vector depending on the surrounding sentence, which is critical for detecting the subtle statistical fingerprints left by LLMs.

**Why AfroXLMR?**
- `Davlan/afro-xlmr-large-61L` is a 561 M-parameter XLM-R model continued-trained on 61 African languages, including Yoruba, Swahili, and languages closely related to isiZulu.
- Strong multilingual cross-lingual transfer; well-suited to our three-language detection task.

**Why AfriBERTa?**
- `castorini/afriberta_large` (126 M parameters) was pre-trained on clean Common Crawl data for 11 African languages including Yoruba and Swahili.
- Smaller footprint means faster Colab fine-tuning with competitive accuracy.

**Approach — following HW3.2:**
Each model is fine-tuned in two ways:

| Variant | Parameters updated | Expected speed |
|---|---|---|
| Full fine-tuning | All (~100 %) | Slower — highest ceiling |
| LoRA (r=4) | ~1–2 % adapter matrices | ~3–5× faster |

Results from all four fine-tuned models are compared against the Section 9 baselines in a single summary table (Section 10.7).

### 10.1 Install and Import Transformer Libraries

Following HW3.2, we install `transformers`, `peft`, `accelerate`, and `evaluate`. `torchao` is upgraded first to avoid a version-compatibility error observed in Colab.

In [ ]:
!pip install -q transformers peft accelerate evaluate
!pip install -q torchao --upgrade   # fixes torchao version errors in Colab

import torch, time
import numpy as np
import evaluate as hf_evaluate
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
)
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
from sklearn.metrics import accuracy_score, f1_score, classification_report
from datasets import Dataset

# Mount Google Drive (safe to re-call if already mounted)
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

MODEL_DIR = '/content/drive/MyDrive/COS760/models'
os.makedirs(MODEL_DIR, exist_ok=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device : {device}")
print(f"PyTorch: {torch.__version__}")
print(f"Models will be saved to: {MODEL_DIR}")

### 10.2 Convert Train / Test Splits to HuggingFace Dataset Format

The `Trainer` API requires data as HuggingFace `Dataset` objects.  We wrap the `text_train` / `text_test` and `y_train` / `y_test` Series produced in Section 7.  The shared `compute_metrics` function (accuracy + F1) is also defined here and reused by every `Trainer` instance below.

In [ ]:
# Wrap existing pandas Series into HuggingFace Datasets
train_hf = Dataset.from_dict({
    'text':  text_train.tolist(),
    'label': y_train.tolist(),
})
test_hf = Dataset.from_dict({
    'text':  text_test.tolist(),
    'label': y_test.tolist(),
})

print(f"Train HF dataset : {len(train_hf):,} rows")
print(f"Test  HF dataset : {len(test_hf):,} rows")
print(f"Features         : {train_hf.features}")

# ── shared compute_metrics (accuracy + F1) used by every Trainer ──────────────
_accuracy_metric = hf_evaluate.load('accuracy')

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = _accuracy_metric.compute(predictions=preds, references=labels)['accuracy']
    f1  = f1_score(labels, preds, average='binary')
    return {'accuracy': acc, 'f1': f1}

### 10.3 AfroXLMR — Full Fine-Tuning

All 561 M parameters are updated.  Following HW3.2: `num_train_epochs=3`, `per_device_train_batch_size=4`, `eval_strategy="epoch"`, `load_best_model_at_end=True`.  Training time is captured with `time.time()`.  The entire cell is wrapped in `try/except` so an OOM or timeout does not prevent the rest of the notebook from running.

In [ ]:
afroxlmr_full_results = {'accuracy': None, 'f1': None, 'time': None}

try:
    model_id_1   = 'Davlan/afro-xlmr-large-61L'
    SAVE_1F      = f'{MODEL_DIR}/afroxlmr_full'
    print(f"=== AfroXLMR — Full Fine-Tuning ===")
    print(f"Model: {model_id_1}")

    # ── tokenizer + tokenized splits ──────────────────────────────────────────
    tokenizer_1 = AutoTokenizer.from_pretrained(model_id_1)

    def _tok1(batch):
        return tokenizer_1(batch['text'], truncation=True,
                           padding='max_length', max_length=128)

    train_tok_1 = train_hf.map(_tok1, batched=True)
    test_tok_1  = test_hf.map(_tok1,  batched=True)
    train_tok_1.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])
    test_tok_1.set_format( 'torch', columns=['input_ids', 'attention_mask', 'label'])

    # ── model — all parameters trainable ──────────────────────────────────────
    model_full_1 = AutoModelForSequenceClassification.from_pretrained(
        model_id_1, num_labels=2,
        id2label={0: 'human', 1: 'machine'},
        label2id={'human': 0, 'machine': 1},
    )
    for p in model_full_1.parameters():
        p.requires_grad = True

    trainable = sum(p.numel() for p in model_full_1.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model_full_1.parameters())
    print(f"Trainable parameters: {trainable:,} / {total:,}  ({100*trainable/total:.1f}%)")

    # ── TrainingArguments (HW3.2 pattern) ─────────────────────────────────────
    args_full_1 = TrainingArguments(
        output_dir='./afroxlmr_full',
        num_train_epochs=3,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=8,
        eval_strategy='epoch',
        save_strategy='epoch',
        load_best_model_at_end=True,
        metric_for_best_model='f1',
        greater_is_better=True,
        logging_steps=50,
        report_to='none',
    )

    trainer_full_1 = Trainer(
        model=model_full_1,
        args=args_full_1,
        train_dataset=train_tok_1,
        eval_dataset=test_tok_1,
        compute_metrics=compute_metrics,
        data_collator=DataCollatorWithPadding(tokenizer_1),
    )

    t0 = time.time()
    trainer_full_1.train()
    elapsed = time.time() - t0

    eval_out = trainer_full_1.evaluate()
    afroxlmr_full_results = {
        'accuracy': eval_out['eval_accuracy'],
        'f1':       eval_out['eval_f1'],
        'time':     elapsed,
    }
    print(f"\n  Accuracy : {afroxlmr_full_results['accuracy']:.4f}")
    print(f"  F1       : {afroxlmr_full_results['f1']:.4f}")
    print(f"  Time     : {elapsed:.0f}s  ({elapsed/60:.1f} min)")

    model_full_1.save_pretrained(SAVE_1F)
    tokenizer_1.save_pretrained(SAVE_1F)
    print(f"  Saved to {SAVE_1F}")

except Exception as e:
    print(f"[ERROR] AfroXLMR Full Fine-Tuning failed: {e}")
    import traceback; traceback.print_exc()

### 10.4 AfroXLMR — LoRA Fine-Tuning

Following HW3.2's LoRA setup exactly: `r=4`, `lora_alpha=16`, `target_modules=["query", "value"]`, `task_type=SEQ_CLS`.  Only the small adapter matrices are trained; the 561 M base weights stay frozen.  `print_trainable_parameters()` shows the dramatic reduction compared to full fine-tuning.  `torchao` is upgraded again here — Colab may reset the pip state between cells.

In [ ]:
!pip install -q torchao --upgrade   # re-run — Colab may reset pip state between cells

afroxlmr_lora_results = {'accuracy': None, 'f1': None, 'time': None}

try:
    SAVE_1L = f'{MODEL_DIR}/afroxlmr_lora'
    print("=== AfroXLMR — LoRA Fine-Tuning ===")

    # ── fresh base model (never load on top of the full fine-tuned one) ────────
    base_lora_1 = AutoModelForSequenceClassification.from_pretrained(
        model_id_1, num_labels=2,
        id2label={0: 'human', 1: 'machine'},
        label2id={'human': 0, 'machine': 1},
    )

    # ── LoRA config — identical to HW3.2 ──────────────────────────────────────
    lora_cfg_1 = LoraConfig(
        r=4,
        lora_alpha=16,
        target_modules=['query', 'value'],
        lora_dropout=0.1,
        bias='none',
        task_type=TaskType.SEQ_CLS,
    )
    model_lora_1 = get_peft_model(base_lora_1, lora_cfg_1)
    model_lora_1.print_trainable_parameters()

    args_lora_1 = TrainingArguments(
        output_dir='./afroxlmr_lora',
        num_train_epochs=3,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=8,
        eval_strategy='epoch',
        save_strategy='epoch',
        load_best_model_at_end=True,
        metric_for_best_model='f1',
        greater_is_better=True,
        logging_steps=50,
        report_to='none',
    )

    trainer_lora_1 = Trainer(
        model=model_lora_1,
        args=args_lora_1,
        train_dataset=train_tok_1,   # reuse tokenized splits from 10.3
        eval_dataset=test_tok_1,
        compute_metrics=compute_metrics,
        data_collator=DataCollatorWithPadding(tokenizer_1),
    )

    t0 = time.time()
    trainer_lora_1.train()
    elapsed = time.time() - t0

    eval_out = trainer_lora_1.evaluate()
    afroxlmr_lora_results = {
        'accuracy': eval_out['eval_accuracy'],
        'f1':       eval_out['eval_f1'],
        'time':     elapsed,
    }
    print(f"\n  Accuracy : {afroxlmr_lora_results['accuracy']:.4f}")
    print(f"  F1       : {afroxlmr_lora_results['f1']:.4f}")
    print(f"  Time     : {elapsed:.0f}s  ({elapsed/60:.1f} min)")

    model_lora_1.save_pretrained(SAVE_1L)
    tokenizer_1.save_pretrained(SAVE_1L)
    print(f"  Saved to {SAVE_1L}")

except Exception as e:
    print(f"[ERROR] AfroXLMR LoRA failed: {e}")
    import traceback; traceback.print_exc()

### 10.5 AfriBERTa — Full Fine-Tuning

Same training setup as 10.3, using `castorini/afriberta_large` (126 M parameters).  AfriBERTa is a RoBERTa-style model pre-trained on 11 African languages using filtered Common Crawl data. Its smaller size means faster fine-tuning while remaining competitive.

In [ ]:
afriberta_full_results = {'accuracy': None, 'f1': None, 'time': None}

try:
    model_id_2   = 'castorini/afriberta_large'
    SAVE_2F      = f'{MODEL_DIR}/afriberta_full'
    print(f"=== AfriBERTa — Full Fine-Tuning ===")
    print(f"Model: {model_id_2}")

    tokenizer_2 = AutoTokenizer.from_pretrained(model_id_2)

    def _tok2(batch):
        return tokenizer_2(batch['text'], truncation=True,
                           padding='max_length', max_length=128)

    train_tok_2 = train_hf.map(_tok2, batched=True)
    test_tok_2  = test_hf.map(_tok2,  batched=True)
    train_tok_2.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])
    test_tok_2.set_format( 'torch', columns=['input_ids', 'attention_mask', 'label'])

    model_full_2 = AutoModelForSequenceClassification.from_pretrained(
        model_id_2, num_labels=2,
        id2label={0: 'human', 1: 'machine'},
        label2id={'human': 0, 'machine': 1},
    )
    for p in model_full_2.parameters():
        p.requires_grad = True

    trainable = sum(p.numel() for p in model_full_2.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model_full_2.parameters())
    print(f"Trainable parameters: {trainable:,} / {total:,}  ({100*trainable/total:.1f}%)")

    args_full_2 = TrainingArguments(
        output_dir='./afriberta_full',
        num_train_epochs=3,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=8,
        eval_strategy='epoch',
        save_strategy='epoch',
        load_best_model_at_end=True,
        metric_for_best_model='f1',
        greater_is_better=True,
        logging_steps=50,
        report_to='none',
    )

    trainer_full_2 = Trainer(
        model=model_full_2,
        args=args_full_2,
        train_dataset=train_tok_2,
        eval_dataset=test_tok_2,
        compute_metrics=compute_metrics,
        data_collator=DataCollatorWithPadding(tokenizer_2),
    )

    t0 = time.time()
    trainer_full_2.train()
    elapsed = time.time() - t0

    eval_out = trainer_full_2.evaluate()
    afriberta_full_results = {
        'accuracy': eval_out['eval_accuracy'],
        'f1':       eval_out['eval_f1'],
        'time':     elapsed,
    }
    print(f"\n  Accuracy : {afriberta_full_results['accuracy']:.4f}")
    print(f"  F1       : {afriberta_full_results['f1']:.4f}")
    print(f"  Time     : {elapsed:.0f}s  ({elapsed/60:.1f} min)")

    model_full_2.save_pretrained(SAVE_2F)
    tokenizer_2.save_pretrained(SAVE_2F)
    print(f"  Saved to {SAVE_2F}")

except Exception as e:
    print(f"[ERROR] AfriBERTa Full Fine-Tuning failed: {e}")
    import traceback; traceback.print_exc()

### 10.6 AfriBERTa — LoRA Fine-Tuning

Same LoRA configuration as 10.4 applied to AfriBERTa. Because AfriBERTa is smaller (126 M vs 561 M), LoRA training here is very fast while retaining strong performance — the best efficiency trade-off in this notebook.

In [ ]:
!pip install -q torchao --upgrade

afriberta_lora_results = {'accuracy': None, 'f1': None, 'time': None}

try:
    SAVE_2L = f'{MODEL_DIR}/afriberta_lora'
    print("=== AfriBERTa — LoRA Fine-Tuning ===")

    base_lora_2 = AutoModelForSequenceClassification.from_pretrained(
        model_id_2, num_labels=2,
        id2label={0: 'human', 1: 'machine'},
        label2id={'human': 0, 'machine': 1},
    )

    lora_cfg_2 = LoraConfig(
        r=4,
        lora_alpha=16,
        target_modules=['query', 'value'],
        lora_dropout=0.1,
        bias='none',
        task_type=TaskType.SEQ_CLS,
    )
    model_lora_2 = get_peft_model(base_lora_2, lora_cfg_2)
    model_lora_2.print_trainable_parameters()

    args_lora_2 = TrainingArguments(
        output_dir='./afriberta_lora',
        num_train_epochs=3,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=8,
        eval_strategy='epoch',
        save_strategy='epoch',
        load_best_model_at_end=True,
        metric_for_best_model='f1',
        greater_is_better=True,
        logging_steps=50,
        report_to='none',
    )

    trainer_lora_2 = Trainer(
        model=model_lora_2,
        args=args_lora_2,
        train_dataset=train_tok_2,   # reuse tokenized splits from 10.5
        eval_dataset=test_tok_2,
        compute_metrics=compute_metrics,
        data_collator=DataCollatorWithPadding(tokenizer_2),
    )

    t0 = time.time()
    trainer_lora_2.train()
    elapsed = time.time() - t0

    eval_out = trainer_lora_2.evaluate()
    afriberta_lora_results = {
        'accuracy': eval_out['eval_accuracy'],
        'f1':       eval_out['eval_f1'],
        'time':     elapsed,
    }
    print(f"\n  Accuracy : {afriberta_lora_results['accuracy']:.4f}")
    print(f"  F1       : {afriberta_lora_results['f1']:.4f}")
    print(f"  Time     : {elapsed:.0f}s  ({elapsed/60:.1f} min)")

    model_lora_2.save_pretrained(SAVE_2L)
    tokenizer_2.save_pretrained(SAVE_2L)
    print(f"  Saved to {SAVE_2L}")

except Exception as e:
    print(f"[ERROR] AfriBERTa LoRA failed: {e}")
    import traceback; traceback.print_exc()

### 10.7 Final Comparison Table — All Six Models

The table below compares all six models on **Test Accuracy** and **Test F1**. Baselines use the `y_pred` / `y_pred_tfidf` arrays already computed in Section 9; training time is N/A for them (they train in under a second). The table is sorted by F1 descending so the best model appears first. A written conclusion identifying the best model follows the table.

In [ ]:
# ── helper: format float or None ──────────────────────────────────────────────
def _fmt(v, is_time=False):
    if v is None:
        return 'N/A'
    return f'{v:.0f}s' if is_time else f'{v:.4f}'

# ── collect all results ────────────────────────────────────────────────────────
rows = [
    {
        'Model':                 'CountVec + Logistic Regression',
        'Type':                  'Baseline',
        'Accuracy':              _fmt(accuracy_score(y_test, y_pred)),
        'F1':                    _fmt(f1_score(y_test, y_pred)),
        'Training_Time_seconds': 'N/A',
        '_f1_sort':              f1_score(y_test, y_pred),
    },
    {
        'Model':                 'TF-IDF + Logistic Regression',
        'Type':                  'Baseline',
        'Accuracy':              _fmt(accuracy_score(y_test, y_pred_tfidf)),
        'F1':                    _fmt(f1_score(y_test, y_pred_tfidf)),
        'Training_Time_seconds': 'N/A',
        '_f1_sort':              f1_score(y_test, y_pred_tfidf),
    },
    {
        'Model':                 'AfroXLMR  — Full Fine-tuning',
        'Type':                  'Transformer (Full)',
        'Accuracy':              _fmt(afroxlmr_full_results['accuracy']),
        'F1':                    _fmt(afroxlmr_full_results['f1']),
        'Training_Time_seconds': _fmt(afroxlmr_full_results['time'], is_time=True),
        '_f1_sort':              afroxlmr_full_results['f1'] or 0.0,
    },
    {
        'Model':                 'AfroXLMR  — LoRA',
        'Type':                  'Transformer (LoRA)',
        'Accuracy':              _fmt(afroxlmr_lora_results['accuracy']),
        'F1':                    _fmt(afroxlmr_lora_results['f1']),
        'Training_Time_seconds': _fmt(afroxlmr_lora_results['time'], is_time=True),
        '_f1_sort':              afroxlmr_lora_results['f1'] or 0.0,
    },
    {
        'Model':                 'AfriBERTa — Full Fine-tuning',
        'Type':                  'Transformer (Full)',
        'Accuracy':              _fmt(afriberta_full_results['accuracy']),
        'F1':                    _fmt(afriberta_full_results['f1']),
        'Training_Time_seconds': _fmt(afriberta_full_results['time'], is_time=True),
        '_f1_sort':              afriberta_full_results['f1'] or 0.0,
    },
    {
        'Model':                 'AfriBERTa — LoRA',
        'Type':                  'Transformer (LoRA)',
        'Accuracy':              _fmt(afriberta_lora_results['accuracy']),
        'F1':                    _fmt(afriberta_lora_results['f1']),
        'Training_Time_seconds': _fmt(afriberta_lora_results['time'], is_time=True),
        '_f1_sort':              afriberta_lora_results['f1'] or 0.0,
    },
]

comparison_df = (
    pd.DataFrame(rows)
    .sort_values('_f1_sort', ascending=False)
    .drop(columns=['_f1_sort'])
    .reset_index(drop=True)
)

print('=' * 70)
print('  FINAL MODEL COMPARISON  (sorted by F1, descending)')
print('=' * 70)
display(comparison_df)

# ── written conclusion ─────────────────────────────────────────────────────────
best = comparison_df.iloc[0]
print(f"\nConclusion")
print('=' * 70)
print(f"Best model : {best['Model']}")
print(f"  Accuracy : {best['Accuracy']}")
print(f"  F1       : {best['F1']}")
print()
print("Transformer models consistently outperform bag-of-words baselines because they")
print("capture contextual patterns that simple word counts miss — especially the subtle")
print("repetitive phrasing and structural regularity produced by LLMs in African languages.")
print()
print("LoRA matches or approaches full fine-tuning performance at a fraction of the compute")
print("cost, confirming the HW3.2 finding that parameter-efficient fine-tuning is a practical")
print("alternative in resource-constrained (Colab free-tier) settings.")

### 10.8 Per-Language Evaluation — Best Transformer Model

The overall F1 hides per-language variation that matters for an African-language project. We reload the best-performing transformer from Google Drive and run inference separately on Yoruba, isiZulu, and Swahili test sub-sets, filtering with the `lang_test` Series from Section 7. This reveals whether the model is uniformly strong or whether one language is harder to classify — common with lower-resource languages like isiZulu.

In [ ]:
# ── identify best transformer ─────────────────────────────────────────────────
_candidates = {
    'AfroXLMR Full':  (afroxlmr_full_results,  'afroxlmr_full',  'tokenizer_1'),
    'AfroXLMR LoRA':  (afroxlmr_lora_results,  'afroxlmr_lora',  'tokenizer_1'),
    'AfriBERTa Full': (afriberta_full_results,  'afriberta_full', 'tokenizer_2'),
    'AfriBERTa LoRA': (afriberta_lora_results,  'afriberta_lora', 'tokenizer_2'),
}
_tok_map = {'tokenizer_1': tokenizer_1, 'tokenizer_2': tokenizer_2}

best_name = None
best_f1   = -1.0
best_save = None
best_tok  = None

for name, (res, save_sub, tok_key) in _candidates.items():
    if res['f1'] is not None and res['f1'] > best_f1:
        best_name = name
        best_f1   = res['f1']
        best_save = save_sub
        best_tok  = _tok_map[tok_key]

if best_name is None:
    print("No transformer model completed training — skipping per-language evaluation.")
else:
    print(f"Best transformer model: {best_name}  (overall F1={best_f1:.4f})")
    print(f"Reloading from: {MODEL_DIR}/{best_save}\n")

    best_model = AutoModelForSequenceClassification.from_pretrained(
        f'{MODEL_DIR}/{best_save}'
    ).to(device)
    best_model.eval()

    # ── evaluate per language ──────────────────────────────────────────────────
    LANG_MAP = {'yor': 'Yoruba', 'zul': 'isiZulu', 'swa': 'Swahili'}
    lang_rows = []

    for lang_code, lang_name in LANG_MAP.items():
        mask     = (lang_test == lang_code).values
        texts_l  = text_test[mask].tolist()
        labels_l = y_test[mask].tolist()

        if len(texts_l) == 0:
            print(f"  {lang_name}: no test samples — skipping.")
            continue

        # batch inference (batch_size=32 to avoid OOM)
        all_preds = []
        for start in range(0, len(texts_l), 32):
            enc = best_tok(
                texts_l[start:start + 32],
                return_tensors='pt',
                truncation=True,
                padding='max_length',
                max_length=128,
            ).to(device)
            with torch.no_grad():
                logits = best_model(**enc).logits
            all_preds.extend(torch.argmax(logits, dim=-1).cpu().numpy().tolist())

        acc = accuracy_score(labels_l, all_preds)
        f1  = f1_score(labels_l, all_preds, average='binary')
        lang_rows.append({
            'Language':     lang_name,
            'Accuracy':     f'{acc:.4f}',
            'F1':           f'{f1:.4f}',
            'Test samples': len(labels_l),
        })

        print(f"{'='*55}")
        print(f"  {lang_name} ({lang_code})  —  n={len(labels_l)}")
        print(f"{'='*55}")
        print(classification_report(
            labels_l, all_preds,
            target_names=['human (0)', 'machine (1)'], digits=4,
        ))

    print("\nPer-language summary:")
    display(pd.DataFrame(lang_rows))